Skyscanner/backpack-ios

Backpack.podspec
Backpack/Classes/Backpack.h
CHANGELOG.md
Example/Backpack/BPKAppDelegate.m
Example/Podfile.lock

This makes sure you can also use the root pod correctly with `pod 'Backpack'` and `#import <Backpack/Backpack.h>`.

[No JIRA] Make sure root pod works

---

Backpack/Classes/Font/Generated/BPKFont.h
Backpack/Classes/Font/Generated/BPKFont.m
Example/Tests/BPKFontTest.m
gulpfile.js
templates/BPKFont.h.njk
templates/BPKFont.m.njk

This will make it easier to support `BPKLabel` with a costructor like
`BPKLabel initWithFontStyle:BPKFontStyleTextSm` etc.

[BPK-1844] Add enum creation method for BPKFont

---

Backpack/Card/Classes/BPKDividedCard.h

Make it clearer that the primary view is the leading/top view and the
secondary view is the trailing/bottom view.

[No JIRA] Improve docs for divided card

---

Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKCalendarCell.h
Backpack/Calendar/Classes/BPKCalendarCell.m

This PR implements the ability to select ranges that start and end on the same day. A typical use-case would be a flight where you come back to your home airport on the same day.

same day range selection

---

Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKSimpleDate.h
Backpack/Calendar/Classes/BPKSimpleDate.m
Example/SnapshotTests/BPKCalendarSnapshotTest.m

This PR changes the calendar to use manual layout rather than Auto Layout as Auto Layout and Yoga don't play well together.
Fix a bug were `setSelectedDates:` would reselect all dates which causes the following visual issue when controlled from React Native

[BPK-2126] Prepare BPKCalendar for RN use

---

Backpack/Calendar/Classes/BPKCalendar.h
UNRELEASED.md

Expose the `NSCalendar` instance used internall by `BPKCalendar` and
thus `FSCalendar`. This is required for the RN calendar.

[BPK-2126] Expose the `NSCalendar` in `BPKCalendar`

---

Backpack.podspec
Backpack/Badge/Classes/BPKBadge.m
Backpack/Button/Classes/BPKButton.m
Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Card/Classes/BPKCard.m
Backpack/Chip/Classes/BPKChip.m
Backpack/Common.h
Backpack/Dialog/Classes/BPKDialogView.m
Backpack/Gradient/Classes/BPKGradientView.m
Backpack/Icon/Classes/BPKIconView.m
Backpack/Label/Classes/BPKLabel.m
Backpack/Panel/Classes/BPKPanel.m
Backpack/RTLSupport/Classes/UIView+BPKRTL.m
Backpack/Spinner/Classes/BPKSpinner.m
Backpack/Switch/Classes/BPKSwitch.m
Backpack/TextView/Classes/BPKTextView.m
Backpack/Theme/Classes/BPKHongKongThemeContainer.m
Example/Podfile.lock

Ensuring at runtime that all Backpack UI components are being called from the main thread.
_If you are curious about how we review, please read through the [code review guidelines](./CODE_REVIEW_GUIDELINES.md)_

Added main thread assertions

---

Backpack/Button/Classes/BPKButton.m
UNRELEASED.md

When a button was laid out after having and image set and then the image
being set back to `nil` it would not lay out correctly. This was because
we were relying on `self.imageView.image` when determining if the button
had an image. When the image is set to `nil` via `setImage:forState` the
underlying `image` property on `UIImageView` still contains the image
and is thus not `nil`. With this change we use `currentImage` which
correctly determines if and image is set.

[No JIRA] Fix button layout bug

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
Example/Backpack/View Controllers/CalendarViewController.swift
UNRELEASED.md

This will enable more complex interactions with the calendar. example: animated external header

Exposing some of the underlying scrollview's properties as readonly props

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKSimpleDate.h
Backpack/Calendar/Classes/BPKSimpleDate.m
Backpack/Calendar/Classes/Calendar.h
Example/Backpack/View Controllers/CalendarViewController.swift
Example/SnapshotTests/BPKCalendarSnapshotTest.m

The update changes the public interface of the BPKCalendar to surface the selected dates as SimpleDate, instead of NSDate to make it explicit that the values should be timezone independent and less error prone to accidental timezone conversions.

Introducing SimpleDate in BPKCalendar

---

Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/BPKThemeContainerController.h
Example/Backpack/BPKThemeContainerController.m
Example/Backpack/Backpack Native-Bridging-Header.h
Example/Backpack/Base.lproj/Main.storyboard

Wraps the entire example app in a class that allows us to set a theme container. This will be required when we wish to switch themes on the fly at runtime

[BPK-2245] Add interchangeable theme wrapper to example app

---

Backpack/Calendar/Classes/BPKCalendar.m
Example/Backpack/View Controllers/CalendarViewController.swift
UNRELEASED.md

This change moves the update of the calendar's collectionview from the beginning of a size transition to the end which is the right time to reload the data. This fixes the split screen issues and some weird behaviour on screen rotation.

Layout update issue fixed

---

Backpack/Theme/Classes/BPKDefaultTheme.m
Backpack/Theme/Classes/BPKDohaTheme.m
Backpack/Theme/Classes/BPKHongKongTheme.m
Backpack/Theme/Classes/BPKLondonTheme.m
Backpack/Theme/Classes/BPKThemeDefinition.h

Decided that adding a `themeName` to the theme definition protocol would help for identifying it in settings etc.

[NO-JIRA] Add themeName to theme definition protocol

---

Backpack/Theme/Classes/BPKThemeContainerController.h
Backpack/Theme/Classes/BPKThemeContainerController.m
Example/Backpack/BPKExampleApp.swift
Example/Backpack/Base.lproj/Main.storyboard
Example/Backpack/View Controllers/BPKRootListTableViewController.m

We want to programatically show the settings UI when the settings button is clicked so that we can wrap it in a theme container.

[BPK-2339] Programatically show settings from settings button

---

Backpack/Theme/Classes/BPKThemeContainerController.h
Backpack/Theme/Classes/BPKThemeContainerController.m
Example/Backpack/BPKAppDelegate.m

So we realised that the ThemeContainer being agnostic to the ThemeDefinition was a bit of an oversight. This changes the API to take a themeDefinition. It then creates the appropriate container itself. (Previously consumers would create a themeContainer from the themeDefinition themselves, and pass the container in).
This simplifies the API, and also means we can expose the current themeDefinition.

[BPK-2270] Add theme definition to container controller API

---

.travis.yml

The random NPMJS SSL errors we've seen recently are happening due to the Travis machine having the incorrect time set.
Anyway, this seems to fix it, so 🤷‍♂️

[NO-JIRA] Fix travis system time issue

---

.travis.yml

We realised that we weren't catching breaks to the docs building process in CI as it only gets built when a release is done. This PR adds docs building to the CI process (but not deploying) so that we catch errors earlier.

[NO-JIRA] Add docs build to travis

---

Backpack/Theme/Classes/BPKDefaultThemeContainer.m
Backpack/Theme/Classes/BPKDohaThemeContainer.h
Backpack/Theme/Classes/BPKDohaThemeContainer.m
Backpack/Theme/Classes/BPKHongKongThemeContainer.h
Backpack/Theme/Classes/BPKHongKongThemeContainer.m
Backpack/Theme/Classes/BPKLondonThemeContainer.h
Backpack/Theme/Classes/BPKLondonThemeContainer.m
Backpack/Theme/Classes/BPKTheme.h
Backpack/Theme/Classes/BPKTheme.m
Backpack/Theme/Classes/BPKThemeContainer.h
Backpack/Theme/Classes/BPKThemeContainer.m
Backpack/Theme/Classes/UIView+BPKThemeContainer.h
Backpack/Theme/Classes/UIView+BPKThemeContainer.m
Example/Backpack/Views/BPKTableViewSelectableCell.swift

Food for thought:
- We can traverse the view hierarchy of a given view to find out what theme is the most appropriate.
- What should consumers do to ensure that changes to the view hierarchy result in the correct change to the primary color? Relying on `didChangeTheme` to trigger re-pulling the `primaryColor` will not be 100% reliable. Instead can they just respond to all view hierarchy changes?
- Logic would probably be simpler if we attached themeDefinition to each ThemeContainerView. Then we could simply traverse the hierarchy to find an instance of BPKThemeContainer instead of needing to work out which ViewController is active.
_If you …

[BPK-2270] Primary color utility spike 2

---

Backpack/Button/Classes/BPKButton.m

As far as I can tell, we don't use the selected color value as we disallow setting buttons selected.
I might be missing something crucial though...

[NO-JIRA] Remove selected color from button

---

Backpack/Theme/Classes/BPKThemeContainerController.m
UNRELEASED.md

Some apps make assumptions about the selectors available on
`keyWindow.rootViewController`. `BPKThemeContainerController` now
handles this better in release builds by not crashing and forwarding the
selector. In debug builds this causes an assertion failure.

[BPK-2320] Forward selectors in Theme Container

---

Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKCalendarCell.m
UNRELEASED.md

Previously the BPKCalendarCell labels simply read out the number displayed. Now they also provide voiceover with the date and year.

[NO-JIRA] Add accessibility labels to calendar dates

---

Backpack/Theme/Classes/BPKSilverTheme.h
Backpack/Theme/Classes/BPKSilverTheme.m
Backpack/Theme/Classes/BPKSilverThemeContainer.h
Backpack/Theme/Classes/BPKSilverThemeContainer.m
Example/Backpack/Settings.storyboard
Example/Backpack/View Controllers/SettingsViewController.swift
Example/Utils/Settings.swift
Example/Utils/ThemeHelpers.swift

I think we should have a theme defined that changes everything that's themeable. In the past we've missed regressions in RN themeability as the themeable property wasn't being showcased anywhere.
Ultimately testing is the way forward for ensuring this all works, but that's not trivial so I think we need to have something to use until it is 👍

[NO-JIRA] Add full theme

---

Example/Backpack/View Controllers/ColorsViewController.swift

Thought it would be good to show off the primary colour on the colours screen, especially now that we're going to support partner theming of all the grays as well - gives us a single place to see them all together...

Show primary color in stories

---

Backpack/Button/Classes/BPKButton.m
UNRELEASED.md

The linkContentColor property on BPKButton is determining tint color for link style buttons, however the setter of this property was calling an update on background and style which are not affected by this property. As a result, the button's content color didn't change until an interaction happened on it. This fix is replacing that call with an update on content color, so when linkContentColor is changed then the visible content color is changing as well. 

[NO-JIRA] linkContentColor setter on BPKButton should update content color

---

Backpack/Button/Classes/BPKButton.m
UNRELEASED.md

Instead of using the end-gradient colour as the pressed state colour, I am instead taking the start gradient colour and combining it with gray900 to be the pressed-state colour. This means that even with a theme applied where start gradient color == end gradient color, there will be a visual difference when pressed.
+ [x] Tests …

[BPK-2829] Fix button pressed state

---

Backpack/NavigationBar/Classes/BPKNavigationBar.m
UNRELEASED.md

Following a suggestion from another dev that proposes to delete the lines where we update `scrollView.contentInset` every time we call `- (void)updateWithScrollView:(UIScrollView *)scrollView` and that gives us a smoother scroll interaction.
+ [ ] Tests
_If you are curious about …

Fixed scrolling using the navigation bar component

---

Backpack/Theme/Classes/BPKContainerController.h
Backpack/Theme/Classes/BPKDefaultTheme.h
Backpack/Theme/Classes/BPKDefaultTheme.m
Backpack/Theme/Classes/BPKThemeContainerController.h
Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native no theme.xcscheme
Example/Backpack/BPKAppDelegate.m
Example/Backpack/View Controllers/BPKRootListTableViewController.m
Example/Utils/ThemeHelpers.swift
UNRELEASED.md

When the example app starts, it immediately applies a theme (even if that theme is `Default`).
This means we have no way of testing our components when un-themed.
As a result - bugs like this cannot be found:
This change ensures that, if no theme is enabled on app start, no theme wrapper will be applied until theming is enabled.
+ [x] Tests …

Enable running the app with no theme enabled

---

Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m

Based on https://github.com/Skyscanner/backpack-ios/pull/400
+ [x] Tests

Fix tappable link label font style with no theme applied

---

Backpack/NavigationBar/Classes/BPKNavigationBar.m
Backpack/NavigationBar/Classes/BPKNavigationBarLargeTitleView.m
Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.m
Example/Backpack/NavigationBar.storyboard
Example/Backpack/View Controllers/NavigationBarViewController.swift
UNRELEASED.md

Some improvements related to the `BPKNavigationBar` component.
Now the `largeTitle` increase/decrease the `fontSize` following the scroll behaviour.
The collapsed title now appears using a fade-in/out animation.
These animations mimic the native navigation behavior.
+ [x] Tests
_If …

 BPKNavigationBar Animations

---

.spelling
Backpack/DarkMode/Classes/DarkMode.h
Backpack/DarkMode/README.md
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native w dark mode.xcscheme
Example/Backpack/Backpack Native-Bridging-Header.h
Example/Backpack/StarRatings.storyboard
Example/Backpack/View Controllers/BPKButtonSelectorViewController.h
Example/Backpack/View Controllers/BPKDarkModeTableViewController.h
Example/Backpack/View Controllers/BPKDarkModeTableViewController.m
Example/Backpack/View Controllers/BPKRootListTableViewController.h
Example/Backpack/View Controllers/BPKRootListTableViewController.m
Example/Backpack/View Controllers/Bottom Sheet/BottomSheetContentViewController.swift
Example/Backpack/View Controllers/Bottom Sheet/BottomSheetViewController.swift
Example/Backpack/View Controllers/CardsSelectorViewController.swift
Example/Backpack/View Controllers/ChipSelectorViewController.swift
Example/Backpack/View Controllers/DialogSelectorViewController.swift
Example/Backpack/View Controllers/FlareViewSelectorViewController.swift
Example/Backpack/View Controllers/GradientSelectorTableViewController.swift
Example/Backpack/View Controllers/HorizontalNavSelectorViewController.swift
Example/Backpack/View Controllers/LabelsSelectorTableViewController.swift
Example/Backpack/View Controllers/PanelSelectorViewController.swift
Example/Backpack/View Controllers/RatingSelectorViewController.swift
Example/Backpack/View Controllers/SettingsViewController.swift
Example/Backpack/View Controllers/TappableLinkLabelsSelectorViewController.swift
Example/Backpack/View Controllers/ToastSelectorViewController.swift
Example/Utils/ThemeHelpers.swift

By default, I have disabled dark mode on all VC's, but it can be enabled with the new Schema `Backpack Native w dark mode`
+ [x] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_RE …

[NO-JIRA] Disable dark mode in example app

---

Example/Tests/BPKLabelTest.m

BPKLabel size tests

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Chip/Classes/BPKChip.h
Backpack/Chip/Classes/BPKChip.m
Backpack/ProgressBar/Classes/BPKProgressBar.h
Backpack/ProgressBar/Classes/BPKProgressBar.m
Backpack/Rating/Classes/BPKRating.h
Backpack/Rating/Classes/BPKRating.m
Backpack/StarRating/Classes/BPKStar.m
Backpack/Switch/Classes/BPKSwitch.h
Backpack/Switch/Classes/BPKSwitch.m
Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.h
Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
Backpack/Theme/Classes/BPKDefaultTheme.m
Backpack/Theme/Classes/BPKThemeDefinition.h

The default theme currently works by applying the default brand colours to every component themeable property. To make theming and dark mode play nicely together, the default theme should be able to simply revert the colour values to `nil` such that the component falls back to the default value itself.
Follow up PR for Calendar...
+ [x] Tests …

[NO-JIRA] Nilify default theme

---

Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/TextField.storyboard
Example/Backpack/View Controllers/TextViewsViewController.swift
Example/Tests/BPKTappableLinkLabelTest.m
Example/Tests/BPKTextFieldTest.m

Some tests were accidentally excluded from the project somehow - probably during a bad rebase?
This PR reinstates them!
+ [x] Tests

[NO-JIRA] Reinstate exluded tests

---

Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.m
UNRELEASED.md

This PR fixes an animation glitch that happens when updating the options in the `HorizontalNavigation`.
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_REVIEW_GUIDELINES.md) …

[AMT-3954] Fix animation glitch when updating `HorizontalNavigation`

---

Backpack/Rating/Classes/BPKRating.m
Backpack/Rating/README.md
UNRELEASED.md

[BPK-3249] Make rating component an accessibility element

---

Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
UNRELEASED.md

[BPK-3415] Calendar month heading RTL alignment

---

Backpack/Font/Classes/Generated/BPKFont.h
Backpack/Font/Classes/Generated/BPKFont.m
Example/Tests/BPKFontTest.m
UNRELEASED.md
templates/BPKFont.h.njk
templates/BPKFont.m.njk

These APIs were removed because our type scale required us to do all
text rendering via attributed string. This is no longer the case so we
can reinstate these APIs.
+ [x] Tests

[No JIRA] Reinstate `UIFont` apis in `BPKFont`

---

.travis.yml

This is what travis provides in the xcode 11.2 image:
https://docs.travis-ci.com/user/reference/osx/#xcode-1121
If we want to build using different SDKs, I think we need to keep using separate xcode images as before.
TL;DR: Don't merge unless @k0nserv is happy to.

[NO-JIRA] Kill xcode 9 builds

---

Backpack/Snackbar/Classes/BPKSnackbar.m
UNRELEASED.md

The logic to search the Tab Bar has changed to support `UITabBar` which is the class that we currently inherit from in the `SKYTabBar` class.
+ [ ] Tests …

Snackbar support UITabBar

---

Example/Backpack NativeUITests/BackpackUITestCase.swift
Example/Backpack NativeUITests/ChipUITest.swift
Example/Backpack NativeUITests/DialogUITest.swift
Example/Backpack NativeUITests/HorizontalNavigationUITest.swift
Example/Backpack NativeUITests/TextFieldUITest.swift
Example/Backpack NativeUITests/TextViewUITest.swift
Example/Backpack NativeUITests/ToastUITest.swift
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/BPKAppDelegate.m
Example/Backpack/Backpack Native-Bridging-Header.h
Example/Backpack/View Controllers/ToastViewController.swift
Example/Utils/UIViewController+UITesting.swift

The UI tests were running with animation at the default speeds which
caused them to take longer to run. Because we don't care about
animations or their durations in UI tests we can disable animations for
UI tests and increase the speed of those animations that aren't disabled
by this.
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a …

[No JIRA] Improve UI tests

---

Backpack/BottomSheet/Classes/BottomSheet.swift
Example/Backpack NativeUITests/BottomSheetUITest.swift
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/View Controllers/Bottom Sheet/BottomSheet.storyboard
Example/Backpack/View Controllers/Bottom Sheet/BottomSheetScrollableContentViewController.swift
Example/Backpack/View Controllers/Bottom Sheet/BottomSheetViewController.swift
UNRELEASED.md

This PR adds an API that allows instantiating and presenting a Bottom Sheet without scrollable content. The height of the bottom sheet will be automatically calculated based on its intrinsic height.
+ [x] Tests …

[BPKR-121] [AMT-4360] Add API for Bottom Sheet with intrinsic size

---

Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.h
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItemDefault.h
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItemDefault.m
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.h
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.m
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOptionType.h
Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationSize.h
Backpack/HorizontalNavigation/Classes/HorizontalNavigation.h
Backpack/HorizontalNavigation/README.md
Example/Tests/BPKHorizontalNavigationTest.m
UNRELEASED.md

Here's the suggested evolution to the current `BPKHorizontalNavigation`
API. It ends up being a breaking change unfortunately but I think in
practice no one relies on the aspects that will break, mainly the change
in type of `options`.
To implement the new badge type we'd create a new option type
`BPKHorizontalNavigationOptionBadge` which adopts the
`BPKHorizontalNavigationOptionType` protocol and returns a new
`UIControl` subclass, `BPKHorizontalNavigationItemWithBadge` from `makeItem`.
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main …

[BPK-3747] Customize horizontal navigation items

---

Backpack/Calendar/Classes/BPKCalendar.m
UNRELEASED.md

This change fixes an issue of Calendar snapping to the closes month header whenever its height changes. The [previous fix](https://github.com/Skyscanner/backpack-ios/pull/218) is only needed when the calendar's width changes, so this fix won't break it.
+ [ ] Tests
_If you are …

[NO-JIRA] Fix Calendar snapping issue

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
UNRELEASED.md

This change makes it possible to modify the calendar's underlying collectionView's contentOffset.
+ [ ] Tests

[NO-JIRA]: Make Calendar contentOffset mutable

---

Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
UNRELEASED.md

Fix a bug where if you set color or size first and then modify navigation options, they will not apply to the new options.
When navigation options change it creates new objects for the new options, but didn't set the correct color and size to these options.
+ [ ] Tests
+ …

[NO-JIRA] Fix HorizontalNavigation color and size setting bug

---

Backpack/Calendar/Classes/BPKCalendar.m
UNRELEASED.md

Fixed an issue when Calendar crashed after these steps:
- Same day is selected, therefore `self.sameDayRange` gets true.
- Selection gets cleared by setting an empty array to `self.selectedDates`, but `self.sameDayRange` remain true because it's not set in line 271
- When `selectedDates` gets called it crashes at line 233 because it tries to add `selectedDates.firstObject` (which has a `nil` value because an empty array was set in the previous step) to an array.
Fixed the issue by setting `self.sameDayRange` to false as well in line 271.
+ [ ] Tests
+ [ ] …

Fix BPKCalendar date selection crash

---

.travis.yml
CHANGELOG.md
CONTRIBUTING.md
Example/Backpack.xcodeproj/project.pbxproj
Example/SnapshotTests/BPKSnapshotTest.h
Rakefile
UNRELEASED.md

Snapshots tests pass now. This is a precursor to releasing the new iOS 12 deployment target.

[No Jira] Bump tests to run on iOS 13.5

---

Backpack/Font/Classes/Generated/BPKFont.h
templates/BPKFont.h.njk

[NO-JIRA] Add font-style docs

---

gulpfile.js

Related to https://github.com/Skyscanner/backpack/pull/2006.
Once those tokens are reinstated, this change will ensure we're still generating and exposing the same set in Objective-C.
+ [x] Tests …

[NO-JIRA] Exclude RN tokens from gulp token generation

---

.github/workflows/ci.yml

When there is a tag, the branch is the tag. So having both these checks results in an always-falsy check.

[NO-JIRA] Deploy tagged docs from any ref

---

.github/workflows/ci.yml

https://github.com/Skyscanner/backpack-ios/runs/1299369560?check_suite_focus=true
If the tests fail...
An asset is created...
Containing the failed snapshots...

[BPK-4256] save snapshots on failure

---

.github/workflows/ci.yml

When we do a release, two CI jobs run. One for the push to master, and one for the push to the tag (because tags are just special branches).
The master run doesn't try to comment on the PR, but the tag one does. I've added an additional check to counter this.

[BPK-4347] Skip comment if tagged

---

Backpack.podspec
Example/Podfile.lock
UNRELEASED.md

No changelog entries: https://github.com/WenchaoD/FSCalendar/blob/master/CHANGELOG.md
All changes: https://github.com/WenchaoD/FSCalendar/compare/2.8.0...2.8.2
Everything seems to work as expected 🤷 
+ [x] Tests …

[BPK-4344] Upgrade FSCalendar to 2.8.2

---

Backpack.podspec
Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
Example/Podfile.lock
UNRELEASED.md

Changelog: https://github.com/TTTAttributedLabel/TTTAttributedLabel/releases/tag/2.0.0
I've enabled `extendsLinkTouchArea` to preserve the existing behaviour because AFAIK it caused no issues and will be more accessible.
+ [x] Tests …

[BPK-4344] Upgrade TTTAttributedLabel to 2.0.0

---

Backpack/Spacing/Classes/Generated/BPKSpacing.h
Backpack/Spacing/Classes/Generated/BPKSpacing.m
gulpfile.js
templates/BPKSpacing.h.njk

I also re-ordered the spacings by value since it was annoying me.
+ [x] Tests …

[No JIRA] Fix docs in BPKSpacing.h

---

Backpack/Calendar/Classes/BPKCalendarCell.m
Example/Backpack/NavigationData.swift
Example/Backpack/ViewControllers/CalendarViewController.swift
UNRELEASED.md

[BPK-4359] Improve calendar dark-mode range color

---

Backpack/BottomSheet/Classes/BottomSheet.swift
Backpack/BottomSheet/Classes/BottomSheetInsets.swift
Backpack/BottomSheet/Classes/ModalBottomSheetLayout.swift
Backpack/BottomSheet/Classes/PersistentBottomSheetLayout.swift
Example/Backpack.xcodeproj/project.pbxproj

This PR introduces an extra `insets` parameter to the BottomSheet initialization call. This allows for greater customization. 
The defaults that were used in ModalBottomSheetLayout and PersistentBottomSheetLayout have been copied over to a new BottomSheetInset struct. 
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Bac …

[NO-JIRA] Add option to customize bottom sheet insets

---

Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/Chips.storyboard
Example/Backpack/NavigationData.swift
Example/Backpack/Stories/ChipStory.swift
Example/Backpack/Story.swift

I've added a new `Story` protocol and `ChipStory` which implements it. The protocol ensures that `presentableStory: Presentable` is implemented, and it also adds adherence to `CaseIterable` and a `storyStructure` property that returns `[Item]`.
This means that the code to add a story can be very simple and all the relevant things – like naming the stories – are abstracted out of `NavigationData`.
The only thing I couldn't figure out was how to make `Story` adhere to `String` so that we don't need to manually add it to each instance.

[BPK-4417] Migrate chip to new navigation story format

---

Backpack/Map/Classes/BPKMapAnnotationView.m

I have updated the constraints for the circleview in the BPKMapAnnotationView.
The way the constraints were setup made it so that the 'parent' view was 0x0 pixels. This made tapping the annotationView almost impossible.
There is still a bug remaining right now, it is not possible to tap the callout price view, as it is 'outside' of the frame of the MKAnnotationView.
I have tried to solve this as well, but my attempts have been fruitless.
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Scree …

Change constraints of dot annotationView

---

Backpack/BottomSheet/Classes/BPKFloatingPanelPosition.swift
Backpack/BottomSheet/Classes/BottomSheet.swift
Backpack/BottomSheet/Classes/BottomSheetInsets.swift
Example/Backpack/ViewControllers/Bottom Sheet/BottomSheetPersistentViewController.swift

I have added a simple delegation passthrough for the moveToPosition call of FloatingPanel. The example is updated to show a possible use case. 
In order to not work with magic numbers I made the fields in BottomSheetInset public so they can be used to update underlaying views or in this example the layoutMargin for the mapView
+ [ ] Tests …

Add delegate for moving the bottom sheet position.

---

Backpack/Map/Classes/BPKMapAnnotationView.m
Example/SnapshotTests/BPKMapAnnotationSnapshotTest.m

[BPK-4416] Fix annotation size

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.m
Backpack/Calendar/README.md
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/ViewControllers/CalendarViewController.swift
Example/SnapshotTests/BPKCalendarSnapshotTest.m
Example/Tests/BPKCalendarSelectionTests.m
UNRELEASED.md

- This PR doesn't change any behaviour.
- The API of the calendar now requites a `selectionConfiguration` instance instead of a `selectionType` enum.
- A follow-up PR will make another breaking change to enforce providing the additional a11y strings required to make this more accessible. 
+ [x] Tests
+ [x] Adding a component? Remember to expose it in the [main `Backpack.h` header …

[BPK-3546] Refactor calendar selection config

---

Example/Backpack/AppStructure.swift
Example/Backpack/Stories/ButtonStory.swift
Example/Backpack/Stories/CalendarStory.swift
Example/Backpack/Stories/CardStory.swift
Example/Backpack/Stories/ChipStory.swift
Example/Backpack/Stories/DialogStory.swift
Example/Backpack/Stories/DividedCardStory.swift
Example/Backpack/Stories/FlareStory.swift
Example/Backpack/Stories/HorizontalNavigationStory.swift
Example/Backpack/Stories/LabelStory.swift
Example/Backpack/Stories/MapStory.swift

The previous method for this used a freestanding function but this made
the code more confusing. By making `enrich` a method the code becomes
simpler and enables chaning. We also don't need `CustomPresentable` in
most cases now.
+ [x] Tests …

[No JIRA] Improve enriching `Presentable`

---

Backpack/Calendar/Classes/BPKCalendar.m
Example/SnapshotTests/BPKCalendarSnapshotTest.m
UNRELEASED.md

Calling `reoadData` on the FSCalendar causes flashing/blinking as found by other consumers:
https://github.com/WenchaoD/FSCalendar/issues/1012
https://github.com/WenchaoD/FSCalendar/issues/1047
+ [x] Tests …

[KOA-4442] Fix blinking on reloadData

---

Example/Backpack/BPKAppDelegate.m
Example/Backpack/ViewControllers/BPKRootTableViewController.swift

The init behaviour in `BPKRootTableViewController` and
`BPKNavigationViewController` was not correct and crashes
with an assertion under iOS 15. We need to explicitly ovveride `init` in
`BPKRootTableViewController`.
+ [x] Tests

[No JIRA] Fix runtime crash in iOS 15

---

.github/dependabot.yml

Adds suppport for NPM and GitHub Actions for dependabot.
Unfortunately dependabot doesn't currently support CocoaPods.

KOA 4726 tweak dependabot

---

CONTRIBUTING.md

Add instructions for taking a one or a few screenshots via the
`take_screenshot` rake task.
+ [x] Tests

[KOA-4746] Add instruction for single screenshot

---

.github/pull_request_template.md
.github/workflows/ci.yml
dangerfile.js

Updated the danger CI token in the PR workflow.
+ [x] Tests

[no jira] Update DANGER_GITHUB_API_TOKEN to GITHUB_TOKEN

---

Backpack/NavigationBar/Classes/BPKNavigationBar.m
Example/Backpack/Stories/NavigationBarStory.swift
Example/Backpack/ViewControllers/NavigationBarViewController.swift

When a tableview with headers is scrolled, the content inset was not changed. This causes the header view to 'float' in the wrong location.
Old behaviour:
Fixed behaviour:
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [ ] Tests
+ [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) …

fix: change content inset when expanding/collapsing navigation bar

---

Backpack/Calendar/Classes/BPKCalendarCell.m

The current UI for same-day return selection isn't consistent with the other platforms. We want to bring these in line so there's consistency with the different calendars
https://gojira.skyscanner.net/browse/WASABI-6040
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [ ] Tests
+ [ ] Docs (either update …

Update Same-Day-Return selection UI to match other platforms

---

Example/Backpack/Labels.storyboard
Example/Backpack/Stories/LabelStory.swift
Example/Backpack/ViewControllers/LabelMultiFontStyleViewController.swift
Example/Backpack/ViewControllers/LabelsPerformanceViewController.swift
Example/Backpack/ViewControllers/LabelsViewController.swift

The api on the Labels was already correct for supporting the new styles. This pr updates the examples of usage of the label to reflect what the new styles are and how they look like.

KOA-4834 new label api

---

Backpack/Font/Classes/Generated/BPKFont.m
UNRELEASED.md
templates/BPKFont.m.njk

fixing bug when attributed text is empty

fixing bug when attributed text is empty

---

Backpack/Button/Classes/BPKButton.h
Backpack/Button/Classes/BPKButton.m
Backpack/Button/Classes/BPKLegacyLinkButton.h
Backpack/Button/Classes/BPKLegacyLinkButton.m
Backpack/Button/Classes/Button.h
UNRELEASED.md

Adding a new BPKLegacyLinkButton to support history use cases on the App, where the usage of Autolayouts (Constraints) is just not compatible and working a hack on the existing button just to keep supporting those usages was not worth it.

Support for Legacy Link Buttons

---

Backpack/Button/Classes/BPKButton.m
UNRELEASED.md

Forwarding calls to `setContentCompressionResistancePriority` and `setContentHuggingPriority` to the inner components of the button to allow clients to properly manage those.

[KOA-4887] Forwarding compression resistance and hugging priority

---

.github/workflows/ci.yml
Backpack/FlareView/Classes/BPKFlarePath.h
Backpack/Icon/Classes/BPKIcon.h

clang-format version was not fixed so it was using a different version on CI than locally, fixing it to the latest so this doesn't happen again, plus fixing the misformatted  files

fixing version of clang to avid unexpected results

---

Backpack/Panel/Classes/BPKPanel.h
Backpack/Panel/Classes/BPKPanel.m
UNRELEASED.md

When creating a BPKPanel in code using `BPKPanel()`, it would not apply any styling to the panel. Only when calling `BPKPanel(padded: true/false)` it would apply the styling.
When inspecting the code there was an 'unavailable' marker for the 'with frame' initializer, but this was ignored by Swift, allowing customers to initialize the panel without passing any parameters and falling back to the frame initializer.
This PR adds the with frame and aligns it with how the BPKCard handles this case. We also took the time to align the docs in the header file with the ones found on BPKCard.
| --------------- | --------------- |
| ![simulator_screenshot_CD5D4001-10B4-4A79-9751-787EAF41E1B5](https://user-images.githubusercontent.com/728889/165008176-95cc3645-806b-44c6-8332-df857f14 …

[NO-JIRA] Fix BPKPanel initializer

---

.github/workflows/ci.yml
Rakefile

Jazzy states in their docs that for combined projects with ObjC and Swift, there's an extra step needed for swift code to be picked up to generate docs. This step is to first create a file that defines how to scan the swift code. SourceKitten plays this role and it's the recommended (by Jazzy) tool for it.
+ [x] Tests
+ [x] Adding a component? Remember to expose it in the [main `Backpack.h` header …

[KOA-4720] adding source kitten to generate swift docs with jazzy

---

.github/workflows/ci.yml

As we are moving towards dependant bumping submodules automatically and we have removed the step in the docs CI to automatically pull latest submodules on main for deployment which can cause unexpected crashes, we are removing the trigger step as this now has no affect on the docs ci

Removing docs site trigger step

---

Example/Backpack/ViewControllers/Tokens/SpacingTokensView.swift

The demo for the BPKSpacing was broken after introducing the new tokens
| Before | After | 
| --- | --- |
| ![simulator_screenshot_242146AC-1F4E-41EE-B3A6-D9A6F96ADD1C](https://user-images.githubusercontent.com/728889/167247236-87681957-08dd-4538-8a3d-c22cf9776f52.png) | ![simulator_screenshot_80DC7783-A772-48CD-83A4-FAE140020948](https://user-images.githubusercontent.com/728889/167247257-088e6f3f-b73d-4bc8-b030-2b57fda96e66.png) |
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Screenshots …

fix: spacings preview

---

Example/Backpack/SwiftUI/Components/Icons/IconsExampleView.swift

The SwiftUI example view did not filter correctly. This PR should resolve that issues
| Before  | After |
| ------------- | ------------- |
| ![simulator_screenshot_7F4F141A-980F-4A0D-AE39-0DC24161286F](https://user-images.githubusercontent.com/728889/169973707-ed4a9aae-8632-4891-a478-2a20f7c93a80.png)  | ![simulator_screenshot_CE92173D-C1EC-46F3-A0C4-402D39C3BC6C](https://user-images.githubusercontent.com/728889/169973247-4c336fc2-ebd3-4097-b6e0-c2f2abe8ff3b.png)  |
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Examp …

NOJIRA Fix icons filtering in swiftui example view

---

.github/workflows/_build.yml
.github/workflows/release.yml

We need to add the Publishing environment when releasing the build step
+ [ ] Tests …

KOA-5168 add environment to build step when releasing

---

Backpack-SwiftUI/Icons/Classes/BPKIconView.swift

The current iconview did not allow for the icon to be changed after the view was created. In order to facilitate this, we changed from from var to let.
This allows for size and icon changes when the binding changes. 
+ [ ] Tests
+ [ ] Docs (either update …

SwiftUI BPKIconView improved API

---

Backpack/Tests/SnapshotTests/Utils/AssertSnapshot.swift

KOA-5373 - Epic
created a helper function for taking and comparing snapshots. To be used by all tests

[KOA-5373] assertSnapshot helper function to use in all tests

---

.github/workflows/release.yml

KOA-5668
Separating the release of the different modules into separate workflows that can execute in parallel, but also be re-runnable in isolation if they fail for any reason

[KOA-5668] Separating releases into different jobs

---

.github/workflows/_build.yml

Clang format 14 was removed from brew, so our installation of it fails, liberating the version as we want to be using the latest all the time anyways

liberating clang format version

---

Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
Backpack/Color/Classes/Generated/BPKColor.h
templates/BPKColor.h.njk
templates/swiftui/DynamicColors.njk

KOA-5736
Deprecating dynamicColor methods to discourage its usage and enable it's future removal/make internal.

[KOA-5736] Deprecating dynamicColor

---

CONTRIBUTING.md

In a recent PR #1565 I required to update the Screenshots as part of the visual change. Whilst following the Contribution guide I found the mention of the file to update to run screenshots, pointed me to a file that didn't match the instructions and confused me when it mentioned 'as per the guide'.  
This change clarifies the file to update and mentions 'comment guide' for awareness rather than a full separate doc to read

Screenshot docs enhancement

---

Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
Backpack/Badge/Classes/Badge.swift

The outline of the accessibility marquee for the badge was focusing on the label and not the entire badge. With this PR we fix UIKit and SwiftUI to have the correct behaviour. 
| Before | After | 
| --- | --- |
| ![IMG_C8749D847A68-1](https://user-images.githubusercontent.com/728889/219871377-05cc2e28-63dd-4408-8e98-302479b0640c.jpeg) | ![IMG_6DA9906A31C4-1](https://user-images.githubusercontent.com/728889/219871264-a4aaf6fe-7e4d-4012-8204-aec681760738.jpeg) |
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Scre …

BPKBadge accessibility outline

---

Backpack/Carousel/Classes/CarouselPageViewController.swift

As discussed and agreed here: https://skyscanner.slack.com/archives/C04NDB73D8S/p1676459363098889?thread_ts=1676046304.364759&cid=C04NDB73D8S

BPKCarousel: Disabling scrolling when setting one image

---

Example/Backpack/Utils/FeatureStories/ComponentCells.swift

One of our files grew larger than allowed, we have added an ignore rule for now as a stopgap measure
+ [ ] Tests

Fix linting issues

---

Backpack/Price/Classes/BPKPrice.swift
Backpack/Rating/Classes/BPKRating.swift
Backpack/Tests/SnapshotTests/BPKPriceSnapshotTest.swift
Backpack/Tests/SnapshotTests/BPKRatingSnapshotTest.swift
Example/Backpack/UIKit/Components/Price/PriceExampleViewController.swift
Example/Backpack/UIKit/Components/Rating/RatingsViewController.swift

Came across some unexpected behaviour and requirements when using BPKPrice and BPKRating components for the hotels itinerary card (S2L):
Changes are:
BPKPrice:
- Update view state when setting a new value to properties
BPKRating: 
- Allow init of component without having to add values for properties. Often, such as in my case now I don't have the data required to pass in yet. 
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main …

[NoJira] Enabling updates of price related values

---

Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
Backpack-SwiftUI/Button/Classes/BPKButton.swift
Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
Backpack-SwiftUI/Panel/README.md
Backpack-SwiftUI/Price/Classes/BPKPrice.swift
Backpack-SwiftUI/Rating/Classes/BPKRating.swift
Backpack-SwiftUI/Skeleton/Classes/BPKSkeleton+Size.swift
Backpack-SwiftUI/Spacing/Classes/BPKSpacing+Extensions.swift
Backpack-SwiftUI/Spacing/Classes/Generated/BPKSpacing.swift
Backpack-SwiftUI/Tests/Rating/BPKRatingTests.swift
Example/Backpack/SwiftUI/Components/Panel/PanelExampleView.swift
Example/Backpack/SwiftUI/Components/Price/PriceExampleView.swift
Example/Backpack/SwiftUI/Components/Rating/RatingExampleViewWithImage.swift
Example/Backpack/SwiftUI/Components/Rating/RatingExampleViewWithTitle.swift
Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
templates/swiftui/Spacing.njk

This PR adds a set of extensions to SwiftUI structs, enabling them to use Backpack tokens instead of points. This change will improve consistency and flexibility across the app's UI components. Additionally, code documentation has been added to these extensions to parallel Apple's documentation with our own extensions. This will help developers better understand how to use these extensions and improve code maintainability.

[KOA-5958] Swiftifying token usage and adding documentation to extensions

---

Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
Example/Backpack NativeUITests/HorizontalNavigationUITest.swift

Added the `.tabBar` trait, so people are informed the navigation behaves like a tabbar. 
This will announce "tab x of y" which makes it easier to understand the layour of the page. 
| --- | --- |
| ![IMG_F9EC8D7FAAE6-1](https://user-images.githubusercontent.com/728889/230325925-95d4f493-8a17-4291-a884-44be31d22ecc.jpeg) | ![IMG_2C0DB6F84FAF-1](https://user-images.githubusercontent.com/728889/230325601-5d2aae12-a3e0-45ce-b93c-d87a1face58f.jpeg) |
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/ …

BPKHorizontal navigation Accessibility fix

---

Backpack/FlightLeg/Classes/BPKFlightLeg.swift

BPKFlightLeg used to accept a carrierLogo of type UIImage?, but it requires an async call to be made to pull an image. To avoid creating another FlightLeg the change will allow the image to be set later once it's available. 
No new snapshots as there is no visual change.

Allow the carrierLogo to be set at a later stage

---

Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
Backpack/Color/Classes/Generated/BPKColor.h
Backpack/Color/Classes/Generated/BPKColor.m
Backpack/Color/Classes/Generated/UIColor+Backpack.h
Backpack/Color/Classes/Generated/UIColor+Backpack.m
Example/Backpack/SwiftUI/Tokens/ColorTokensView.swift
package-lock.json
package.json

Introduce a new `.surfaceSubtleColor` token into the codebase.
| Day | Night |
| --- | --- |
| <img width="347" alt="image" src="https://user-images.githubusercontent.com/728889/234194633-cbb797b1-2c74-4da1-8999-fef4c669f623.png"> | <img width="345" alt="image" src="https://user-images.githubusercontent.com/728889/234194652-09ee2419-22f2-4641-9876-7c8512401427.png"> |
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` …

KOA-6066 Introduce new color token

---

Backpack/FlightLeg/Classes/BPKFlightLeg.swift

Currently when displaying the FlightLeg component in S2L the content mode of the carrier logo is stretched. 
+ [ ] Tests

Setting BPKFlightLeg imageView contentMode to aspectFit

---

Backpack-SwiftUI/Utils/Classes/View+SizeCategory.swift

Add util from public source to make sure we can clamp Dynamic type sizing
+ [ ] Tests

KOA-5976 Dynamic type util

---

Backpack-SwiftUI.podspec
Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
Backpack-SwiftUI/Button/Classes/BPKButton.swift
Backpack-SwiftUI/Chip/Classes/BPKChip.swift
Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
Backpack-SwiftUI/Chip/Classes/BPKDropdownChip.swift
Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
Backpack-SwiftUI/Price/Classes/BPKPrice.swift
Backpack-SwiftUI/Rating/Classes/BPKRating.swift
Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift
Backpack-SwiftUI/Utils/Classes/ScaledFont.swift
Example/Podfile
Example/Podfile.lock

To make the process smoother, we limit all components to scale, as before. We will then unlock components case-by-case
+ [ ] Tests

KOA-5976 Make all SwiftUI components not scale

---

Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift

The gesture over the BPKDismissableChip to emulate the highlighted effect broke scrolling. By removing this gesture we fix this, but remove the highlighing over the (X) button on the chip, a very minor drawback to unblock this.

Removing gesture from dismissable chip

---

Backpack-SwiftUI/Badge/Classes/BPKBadge.swift
Backpack-SwiftUI/Chip/Classes/BPKChip.swift
Backpack-SwiftUI/Chip/Classes/BPKDismissableChip.swift
Backpack-SwiftUI/Chip/Classes/BPKDropdownChip.swift
Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
Backpack-SwiftUI/ChipGroup/Classes/BPKStickyChip.swift
Backpack-SwiftUI/Font/Classes/BPKFont.swift
Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
Backpack-SwiftUI/Price/Classes/BPKPrice.swift
Backpack-SwiftUI/Rating/Classes/BPKRating.swift
Backpack-SwiftUI/Switch/Classes/BPKSwitch.swift

- Allow BPKBadge to scale properly
- Introduce BPKFont.setDyamicType(enabled:Bool) to configure dynamic type
+ [ ] Tests

KOA-5977 BPKBadge dynamic type fixes

---

Backpack/Price/Classes/BPKPrice.swift

Alignment of label would fail when trailing label was set to nil / receiving content.
We now remove the view instead of hiding when the label becomes nil to prevent ambiguos layouts
+ [ ] Tests …

BPKPrice fix

---

Backpack-SwiftUI/Icons/Classes/BPKIconView.swift

The icon view did not use the `decorative:` initializer, where we want our icons to be decorative by default. 
+ [ ] Tests

SwiftUI BPKIconView

---

Backpack/Font/Classes/BPKFontManager.h
Backpack/Font/Classes/BPKFontManager.m
Backpack/Font/Classes/Generated/BPKFont.h
Backpack/Font/Classes/Generated/BPKFont.m
Backpack/Label/Classes/BPKLabel.m
Backpack/Tests/UnitTests/BPKFontTest.m
Example/Backpack/AppDelegate.swift
scripts/gulp/fonts.js
templates/BPKFont.h.njk
templates/BPKFont.m.njk

Add a config option to allow dynamic type for Backpack (UIKit) components. There have been no change to components (so far). This is just to allow resizing. 
Future commits will deal with appearances
+ [ ] Tests …

KOA-6275 Add dynamic font config for Backpack (UIKit)

---

Backpack/Button/Classes/BPKButton.m
Backpack/Tests/UnitTests/BPKButtonTest.swift

The accessibility label of the BPKButton would be reset when any style change was applied. This is now resolved and tests have been added to prevent regressions
+ [ ] Tests …

[BugFix] BPKButton accessibility label

---

Backpack-SwiftUI/Dialog/Classes/BPKDialogView.swift
Backpack-SwiftUI/Dialog/Classes/DialogContainerViewModifier.swift
Backpack-SwiftUI/Dialog/Classes/UIKitDialogContainerViewModifier.swift
Example/Backpack Screenshot/SwiftUIScreenshots.swift
Example/Backpack/SwiftUI/Components/Dialog/DialogExampleView.swift

Adding a SwiftUI version of the dialog component, which can be used as a ZStack of views instead of a view controller. The SwiftUI dialog uses the same content and actions views as the UIKit dialog, but wraps them in a custom modifier that handles the presentation logic.
This is meant to be used in cases where presenting a view controller is not an option. The example use case for Hotels is that we need to show a dialog on a screen that's currently presenting a screen, making a new presentation impossible.
This, being just a view, has a couple of drawbacks, like presentation events for accessibility, which needs to now be done manually from the client or the scrim not being able to be drown on top of a tab bar controller or a nav bar.
So, the usage of this component is not encouraged, but …

Adding a swiftui version of the dialog used as a zstack of views

---

Backpack/Font/Classes/Generated/BPKFont.m
Backpack/Label/Classes/BPKLabel.m
templates/BPKFont.m.njk

The way we handled the scaling would erase custom attributedText. 
For now, we forego the custom lineheights when DynamicType is on, as a test with our custom font. Once we prove it works, we can remove custom lineheights at all times.
+ [ ] Tests
_If you are curious about how we review, please read …

[BugFix] DynamicType and AttributedText

---

Backpack/Chip/Classes/BPKChip.swift
Example/Backpack/UIKit/Components/Chip/ChipsViewController.swift

- Add proper resizing for BPKChip (adding a 4pt margin on larger sizes)
- Allow for height to grow beyond the default of 32pt
- Update example view to allow proper scaling (Scrollview + Axis change)
+ [ ] Tests …

[DynamicType] BPKChip

---

Backpack/Calendar/Classes/BPKCalendar.h
Backpack/Calendar/Classes/BPKCalendar.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.m
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.h
Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.m
Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
Backpack/Calendar/Classes/BPKCalendarWholeMonthSelectionConfiguration.swift
Backpack/Calendar/Classes/BPKYearMonth.swift
Backpack/Calendar/README.md
Backpack/Tests/SnapshotTests/BPKCalendarSnapshotTest.swift
Backpack/Tests/UnitTests/BPKCalendarWholeMonthConfigurationTests.swift
Backpack/Tests/UnitTests/BPKYearMonthTests.swift
Example/Backpack/UIKit/Components/Calendar/CalendarViewController.swift

OGM-1926
We want to disable the last month button as it select the actual month instead. 
To fix this issue we decided to disable it for now.
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REV …

OGM-1926: Disable month selection for last month

---

Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleRangeView.swift
Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleSingleView.swift

This is a fix for Calendar Header Formatting that can be reproduced in a particular situation (possibly others as well)
* Set the (Swift)Calendar used to create the (Backpack)BPKCalendar to a UTC calendar (In Skyscanner there are situations where we present dates in a UTC timezone).
* Set the device _time_ to 1st day of the month before 11am
* Set the device _timezone_ to Honolulu (you will see your system lock change to the _last day of the month before_
The calendar opens and even though the 1st month being displayed is correct, E.g. in the example below, the 1st month being displayed is December, the _Header_ is incorrect Where it displays "November 2023" this should read "December 2023"
* Used the same timezone for the date formatter in the example view so these dates are also …

fix: LMN-806 use timezone for month formatter

---

scripts/ci

This pull request disables the `uitests` ran in PRs. This module is currently causing issues/flakiness and needs to be temporarily disabled. Once the issues/flakiness are resolved, the tests can be re enabled

Comment out "uitests" module in CI script

---

Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModalResults.swift

Conform BPKAppSearchModalResults to Equatable
Even if we can do it outside the module by making all the properties public, but it's verbose.
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVI …

Conform BPKAppSearchModalResults to Equatable

---

Backpack/Carousel/Classes/BPKCarousel.swift

- Fix the issue which swiping BPKCarousel doesn't update the pageIndicator when its delegate is nil
+ [ ] Tests

SONIC-2126: BPKCarousel page indicator should update when delegate = nil

---

Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/SwiftUI/Components/AppSearchModal/AppSearchModalExampleView.swift
Example/Backpack/SwiftUI/Components/AppSearchModal/AppSearchModalExampleViewModel.swift
Example/Backpack/Utils/FeatureStories/Groups/AppSearchModalGroups.swift

In the view BPKAppSearchModal we draw a BPKTextField when the state is loading or content.
Previously this was done through a switch statement, so SwiftUI was unable to identify that we wanted this to be the _same_  BPKTextField.
Now for both loading & content states, we render the same BPKTextField using an 'if' statement based on content state instead of within the 'switch' statement, this informs Swift UI that it doesn't need to redraw the BPKTextField when changing between loading and content states.
+ [ ] Tests
+ [ ] [Screenshotting …

fix: LMN-925 BPKAppSearchModal recreating TextField when changing from loading to content

---

Backpack-Common.podspec
Backpack-Fonts/Backpack-Fonts.podspec
Backpack-SwiftUI.podspec
Backpack.podspec
Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
Backpack/Color/Classes/Generated/BPKColor.m
Example/Backpack Screenshot/SnapshotHelper.swift
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/UIKit/Components/Link/TappableLinkLabelsViewController.swift
Example/Podfile
Example/Podfile.lock
scripts/lint

This pull request updates the iOS deployment targets to 15.1 for all relevant files and dependencies.

Update iOS deployment targets to 15.1

---

Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift

This PR sets a line limit for the subtitle cell in `SearchAppModalContentView` when the dynamic size does not exceed Apple's default size, `Large`.
|    Small      |     Large (Default)    |     Extra Large    |     Accessibility Medium    | 
|---------------------|------------------|------------------|------------------|
| 2 lines  | 2 lines | unlimited lines | unlimited lines  |
|      <img src="https://github.com/Skyscanner/backpack-ios/assets/159815080/fcdfb96b-cc55-4b35-88ab-e5c65294e764" alt="screen-shot" width=“100”/>      |     <img src="https://github.com/Skyscanner/backpack-ios/assets/159815080/c4cc3b7b-1e16-463f-ab0e-93c7570342ca" alt="screen-shot" width=“100”/>    |     <img src="https://github.com/Skyscanner/backpack-ios/assets/159815080/e85dc69c-d476-445e-be6f-334defa94ae7" …

[DON-385] Set line limit in `SearchAppModalContentView` cell's subtitle

---

Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift

- Add `isButton` to each item on the search modal. This indicates the item is tappable
- Add `isSearchField` to the search input, this adds more semantic meaning and sets expectations of the input fields role. 
| Before | After | 
| --- | --- |
| https://github.com/Skyscanner/backpack-ios/assets/728889/3a23a9f4-4147-49bb-92d8-2f8d93d570aa | https://github.com/Skyscanner/backpack-ios/assets/728889/f677afa4-c8f7-4b74-a4b2-3cdc4f5dc60b |
+ [x] Tests
+ [ ] …

ACC-453 / ACC-454 AppSearchModal accessibility fix

---

Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift

- Change the contentShape modifier to apply to the button content, this way the entire button is tappable and not just the text content
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GU …

fix: Move content shape to HSTack to allow custom button to be tappable

---

Backpack-SwiftUI/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
Backpack-SwiftUI/HorizontalNavigation/README.md
Backpack-SwiftUI/Tests/HorizontalNavigation/BPKHorizontalNavigationTests.swift
Example/Backpack/SwiftUI/Components/HorizontalNavigation/HorizontalNavigationExampleView.swift

This pull request refactors the BPKHorizontalNavigation component to include onClick handlers for tab selection. This allows users to interact with the tabs and select a specific tab by clicking on it.
It allows easier and greater flexibility for running specific logic when a tab is selected by the user tapping on it SEPARATELY than from when a tab is selected by code.

Refactor BPKHorizontalNavigation to include onClick handlers for tab selection

---

Example/Backpack Screenshot/Screenshots.swift
Example/Backpack Screenshot/SwiftUIScreenshots.swift
Example/Backpack/SceneDelegate.swift
Example/Backpack/Utils/ThemeHelpers.swift

We published a change 3 weeks ago to force light mode if force_dark_mode was not set, this however forces the example app to always run in light mode and not allow us to test simulator/phone with dark mode. 
I have added a FORCE_LIGHT_MODE equivalent to ensure light mode can be set on UI-tests as well
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/main/Backpac …

Re-enable light/dark mode switching on the example app

---

Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift

The goal is to add accessibility identifiers for AppSearchModal elements which are used in PlaceSelector. It's needed for writing UI tests.
There is an issue with enabling the accessibility trait and keeping the search field hittable for UITests. There is a ticket to investigate that issue: https://skyscanner.atlassian.net/browse/DON-500
+ [ ] Tests …

DON-335: Add accessibility identifiers to PlaceSelector elements

---

Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryGrid.swift
Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryImageGridStyle.swift
Example/Backpack/SwiftUI/Components/ImageGalleryGridView/ImageGalleryGridExampleView.swift

This pull request refactors the BPKImageGalleryImageGridStyle to use structs for chip and image categories. This improves code organization and readability.

Refactor BPKImageGalleryImageGridStyle to use structs for chip and image categories

---

.github/workflows/release.yml

This pull request updates the Xcode version to 14.2 in the GitHub Actions workflow for Releases. This ensures that the correct version of Xcode is used during the release process.

Update Xcode version to 14.2 in GitHub Actions workflow for Releases

---

Backpack-SwiftUI/AppSearchModal/Classes/BPKAppSearchModal.swift
Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
Backpack-SwiftUI/SearchInputSummary/README.md

[DON-491]
Update search modal to fix the test automation
+ [ ] Tests

[DON-491] Update search modal to fix the test automation

---

Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryGrid.swift
Backpack-SwiftUI/ImageGalleryGrid/Classes/BPKImageGalleryImageGridStyle.swift
Backpack-SwiftUI/ImageGalleryGrid/Classes/ImageGalleryGridContentView.swift
Backpack-SwiftUI/ImageGallerySlideshow/Classes/BPKImageGalleryImage.swift
Backpack-SwiftUI/ImageGallerySlideshow/Classes/BPKImageGallerySlideshow.swift
Backpack-SwiftUI/Tests/ImageGalleryGrid/ImageGalleryGridTests.swift
Example/Backpack/SwiftUI/Components/ImageGalleryGridView/ImageGalleryGridExampleView.swift
Example/Backpack/SwiftUI/Components/ImageGallerySlideshow/ImageGallerySlideshowExampleView.swift

This pull request updates the usage of `BPKImageGalleryImage` to `BPKSlideshowGalleryImage` in the SwiftUI components. The changes include updating the struct names, replacing instances of `BPKImageGalleryImage` with `BPKSlideshowGalleryImage`, and updating the references in the tests. This update ensures consistency and improves clarity in the codebase.

Image Grid and Slideshow to use different view builders

---

Backpack/BarChart/Classes/BarChart.swift
Backpack/BarChart/Classes/BarChartBar.swift
Backpack/BarChart/Classes/BarChartCollectionViewCell.swift
Backpack/BarChart/Classes/BarChartCollectionViewDataSource.swift
Backpack/BarChart/Classes/BarChartCollectionViewHeader.swift
Backpack/BarChart/Classes/BarChartKeyItem.swift
Backpack/BarChart/Classes/MiniFlareView.swift
Backpack/Tests/SnapshotTests/BPKBarChartSnapshotTest.swift
Example/Backpack/UIKit/Components/Bar chart/BarChartViewController.swift

- Hide the key items (price/no price) as they add clutter
- Make month titles heading
- Fix accessibility label and value for each bar
| --- | --- |
| [Video before](https://github.com/Skyscanner/backpack-ios/assets/728889/3423049c-5f68-4512-9b22-4fc8bc4e9c99) | [Video after](https://github.com/Skyscanner/backpack-ios/assets/728889/4955ba5f-b40c-461d-8b0f-1e6dcd7c9e54) |
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the …

[BPKBarChart] ACC-455/ACC-456 Resolve Accessibility defects

---

Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationViewItem.swift
Backpack-SwiftUI/NavigationBar/Classes/CollapsedNavigationBar.swift

Hola 👋 
This adds the ability to set accessibilityIDs to the navigation bar items in SwiftUI for UITest purposes
+ [ ] Tests

AI-439 Set an optional accessibilityIdentifier on the button items in the navigation bar

---

Backpack-SwiftUI/Nudger/Classes/BPKNudger.swift
Example/Backpack/SwiftUI/Components/Nudger/NudgerExampleView.swift

In the scope of improving feature tests of the traveller selector there is essential change for BPKNudger, which is using as a stepper component in TravellerSelector.
The problem is some small components like increment and decrement buttons are unavailable for clicking in UITests due to combining those elements into one Nudger accessibility element.
Those changes make smaller elements accessible without any changes for screen reader for actual accessibility users.
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/ …

DON-386: Add accessibility support to BPKNudger

---

.github/workflows/_test.yml
.github/workflows/label-check.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Using the latest ubuntu image for the github runners but using the specific YAML label instead of `latest`
All available images: https://github.com/actions/runner-images?tab=readme-ov-file#available-images

RALP-4865 Use ubuntu-22.04 instead of ubuntu-latest

---

Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift

PAN-2774
As previously mentioned in the ticket, we currently display month names in Finnish (fi-FI) with endings like `maaliskuuta` and `huhtikuuta`. The correct forms should be `maaliskuu` and `huhtikuu` respectively. 
This PR fixes the issue by invoking a system API ([DateFormatter.dateFormat](https://developer.apple.com/documentation/foundation/dateformatter/1408112-dateformat)) to translate the generic format string into a localized date format string.
| -- | -- |
| ![image](https://github.com/user-attachments/assets/d322d9e9-a340-49e4-befb-3312edd2618c) | ![image](https://github.com/user-attachments/assets/4aa49bb9-298b-4db2-9e01-61ee1c18d792) |
+ [x] Check this if you have read and followed the [contributing …

[Panda]PAN-2774: Fix Incorrect month format in calendar view

---

Backpack-SwiftUI/BottomSheet/Classes/BPKBottomSheetContentMode.swift
Backpack-SwiftUI/BottomSheet/Classes/BottomSheetContainerViewModifier.swift
Backpack-SwiftUI/BottomSheet/Classes/ItemBottomSheetContainerViewModifier.swift
Example/Backpack/SwiftUI/Components/BottomSheet/BottomSheetExampleView.swift

This pull request adds the ability to configure the expansion behavior of the medium bottom sheet in the code. Previously, the medium bottom sheet was always expansible, but now it can be set to be non-expansible if desired. This provides more flexibility in customizing the behavior of the medium bottom sheet.

Make medium bottom sheet expansion configurable

---

Backpack-SwiftUI/Button/Classes/BPKButton.swift
Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
Backpack-SwiftUI/Text/Classes/BPKText.swift
Backpack-SwiftUI/TextField/Classes/BPKTextField.swift

We discovered that not all components follow the restriction on DynamicType font scaling. This PR now ensures all components honour the toggle and ensure consistency
+ [ ] Tests …

SwiftUI DynamicType toggle

---

Backpack-SwiftUI/ImageGalleryGrid/Classes/ImageGalleryGridContentView.swift

[[LMN1597]](https://skyscanner.atlassian.net/browse/LMN-1597)
Fixing the problem: When switching tab in the gallery the scroll position gets maintained. It should be reset to 0 to avoid confusion as the content between tabs is different.
+ [x] Tests
_If you are curious about how we review, please …

[LMN1597][BpkImageGalleryGrid] Fix switching reset scroll view position

---

decisions/README.md
decisions/ui-test-accessibility-identifiers.md

Our stance on how we want to enable UI-testing of our components has been unclear in the past. This is leading to different implementations across our components.
This decision doc provides clarity on how we intend to facilitate ui-testing of our components. The full rationale and decision is in the decision doc. A TL;DR is added to the PR description below:
TL;DR
* **Standalone Components**: No accessibility identifiers for UI tests. Consumers can add them as needed.
* **Components in Larger UIs**:
* **Hardcoded identifiers** if the component is used in a single place.
* **Dynamic identifiers** if the component is reused in multiple places. …

Add decision doc for accessibility identifiers in UI-tests

---

Backpack-SwiftUI/ChipGroup/Classes/BPKMultiSelectChipGroup.swift
Example/Backpack/SwiftUI/Components/ChipGroup/MultiSelect/ChipGroupMultipleSelectWrapExampleView.swift

This pull request updates the `BPKMultiSelectChipGroup` to handle the dropdown type in chip items. Previously, the chip group only supported option type chips, but now it also supports dropdown type chips. The `BPKMultiSelectChipGroup` struct has been modified to include a new case for dropdown chips, and the `ChipGroupMultipleSelectWrapExampleView` has been updated to include dropdown chips in its `chipsData` array. This allows users to select and toggle dropdown chips in the chip group.

Update BPKMultiSelectChipGroup to handle dropdown type in chip items

---

Backpack-SwiftUI/CardCarousel/Classes/BPKCardCarousel.swift

Fix BPKCardCarousel's inverted scroll direction in Right to left languages 
|--------|-------|
|  ![before fix](https://github.com/user-attachments/assets/aaf857e0-384f-4007-b7bc-0435b937a6ec)     |  ![after fix](https://github.com/user-attachments/assets/1dffe7da-9c7f-4538-9836-9f79e4036930)  |
- If you want to test it locally, you will need to add arabic & build the Example project 
+ [x] Tests
+ [ ] Adding a component? Remember to …

SONIC-2889: fix BPKCardCarousel's scrolling in right to left languages

---

Backpack-SwiftUI/TextArea/Classes/BPKTextArea.swift

Issue:
Accessibility label was announced twice. 
+ [ ] Tests

No-Jira: Fix text area accessibility

---

Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift

https://skyscanner.atlassian.net/browse/LMN-1700
- We found that the scroll position of content of App Search Modal changes which results in the keyboard dismiss as unexpected.
- To resolve it, add extensions to `CGFloat` and `CGPoint` to compare the 2 points in a certain number of decimal places.
https://github.com/user-attachments/assets/396d6c34-f137-4749-9d52-8b56b72b343d
https://github.com/user-attachments/assets/d838496c-98be-4ea8-803a-1c34e997ea9a
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Screenshot …

[LMN-1700] Fix the keyboard dismisses automatically while typing in App Search Modal

---

Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift

An accessibility identifier required for the automated test has been removed in the following PR:
https://github.com/Skyscanner/backpack-ios/pull/2066/files#diff-0df197ad1c29c184f5dab226161c3658be5fdfffc53bb83d23529f1863aa1300L68
This PR purpose is to bring it back and fix the testing pipeline.
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/main/Backpack/Backp …

Add the missing identifier to SearchInputSummary

---

Backpack-SwiftUI/ImageGallerySlideshow/Classes/BPKImageGallerySlideshow.swift

Recently, we found that the review gallery failed to show image in iOS 18 devices, here we try to resolve it
| -- | -- |
| ![image](https://github.com/user-attachments/assets/4402c123-4306-45c9-b0d0-2de441ffc3c0) | ![image](https://github.com/user-attachments/assets/626e80ef-b123-4b5c-b4b5-52ea6f40db53) |
+ [ ] Tests …

[Lumen] LMN-1740: move geometry reader inside the component

---

Backpack-SwiftUI/Chip/Classes/ChipButtonStyle.swift
Backpack-SwiftUI/FlowStackView/Classes/BPKFlowStackView.swift

**Changes**
* Use `.lineLimit(1)` instead of `.fixedSize(horizontal: true, vertical: false)` in `ChipButtonStyle` so that `BPKChip` will not go beyond its parent due to too long text.
* Fix bug on `BPKFlowStackView` when computing Rows
**Preview**
| ------- | ----- |
| ![](https://github.com/user-attachments/assets/071d4c8a-c159-4bdc-8554-79c541a5871d) | ![](https://github.com/user-attachments/assets/cb665e03-0ec6-4360-8697-71a31cfff656) |
+ [ ] Tests
+ [ ] [Screenshotting code](https://github.com/Skyscanner/backpack-ios/blob/main/Example/Backpack%20Screenshot/Screen …

Fix: BPKChip goes beyond its parent when the text is too long

---

Backpack-SwiftUI/Utils/Classes/TwoRowGrid.swift

LMN-1746
| -- | -- |
| ![backpack-trimmed mp4](https://github.com/user-attachments/assets/976a14bf-e177-4387-8397-388cab9093f0) | ![backpack-fixed mp4](https://github.com/user-attachments/assets/221adad1-5fcf-423f-9d5c-5217591ba495) |
When tapping through the last 4 images in sequence, we can see: tapping the first image triggered an incorrect slideshow modal, before this fix applied.
+ [ ] Tests
+ [ ] Adding a component? Remember to …

[LMN-1746] When user selects an image incorrect picture is brought up.

---

Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/AppDelegate.swift
Example/Podfile
Example/Podfile.lock

The app center cocoapod was in our code, but we never set up app center properly with the secret key.
It's not part of our plist, run scheme or environment on git.
+ [ ] Tests …

Remove app center dependency

---

Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
Backpack-SwiftUI/Calendar/Classes/Core/CalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
Backpack-SwiftUI/Calendar/Classes/Core/MonthScroll.swift
Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleRangeView.swift
Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleSingleView.swift
Example/Backpack/Utils/FeatureStories/Groups/CalendarGroups.swift

This PR is about giving the capability to have Initial scroll in Calendar based on the product alignment.
https://github.com/user-attachments/assets/ddf964e4-aa5a-45f4-8abd-49be6766dae3
+ [ ] Tests …

[DON-962] Initial scroll to month in Backpack Calendar

---

.github/workflows/_build-docs.yml
.github/workflows/_build.yml
.github/workflows/_test.yml
.github/workflows/release.yml

Upgrade all GitHub Actions workflows to run on macOS 15, ensuring compatibility with the latest environment.

Update GitHub Actions to use macOS 15 for all workflows

---

Backpack-SwiftUI/Calendar/Classes/AccessibilityConfigurations/SingleAccessibilityConfigurations.swift
Backpack-SwiftUI/Calendar/Classes/AccessibilityConfigurations/WholeMonthAccessibilityConfigurations.swift
Backpack-SwiftUI/Calendar/Classes/CalendarSelectionType.swift
Backpack-SwiftUI/Calendar/Classes/CalendarSignleSelectionState.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleDayAccessibilityProvider.swift
Backpack-SwiftUI/Tests/Calendar/BPKCalendarTests.swift
Example/Backpack.xcodeproj/project.pbxproj
Example/Backpack/SwiftUI/Components/Calendar/CalendarExampleSingleView.swift

This PR adds the whole month selection as one the single date selection mode states.
https://github.com/user-attachments/assets/04219a04-5a43-4481-99db-1886011849f0

[DON-715] Whole month in single date selection

---

Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift

The `onTapGesture` was added to the wrong place, which prevented us from executing it by double-tappping a BPKDividedCard with VoiceOver on.
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVI …

Fix onTapGesture for BPKDividedCard

---

Backpack-SwiftUI/Calendar/Classes/Core/CalendarContainer.swift

When you provide a month to scroll, it has a weird behaviour when you change a selection in some cases.
LazyVStack should have better optimisation for scroll views and it's recommended using it over VStack.
More info and video with an example: https://skyscanner.atlassian.net/browse/DON-1037
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/main/Backpack/Backpack …

[DON-1037] Fix BPKCalendar scroll view

---

Backpack-SwiftUI/Slider/Classes/BPKRangeSlider.swift
Backpack-SwiftUI/Slider/Classes/BPKSlider.swift
Backpack-SwiftUI/Slider/Classes/BPKSliderHelpers.swift
Backpack-SwiftUI/Tests/Slider/SliderTests.swift
Example/Backpack.xcodeproj/project.pbxproj

The `BPKSlider` does not change value according to drag direction in RTL layouts
https://github.com/user-attachments/assets/25c3af2e-ec08-479f-b17c-842bf996b0f5
**Screen recording after the fix**
RTL
https://github.com/user-attachments/assets/3eed5a6e-7e4e-479c-8e4f-e667dd5b83f1 
LTR
https://github.com/user-attachments/assets/523aed6e-11ff-43aa-afe6-048a7275ccf5
+ [ ] Tests …

Fix drag direction issue in BPKSlider for RTL layouts

---

Backpack-SwiftUI/Icons/Classes/BPKIcon.swift
Backpack-SwiftUI/Icons/Classes/BPKIconView.swift
Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
templates/swiftui/BPKIcons.njk

Update BPKIcon to make the bundle parameter optional, set a default bundle if none is provided, and refactor the initializer for improved readability.

Make bundle parameter optional in BPKIcon methods

---

Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
Backpack/Color/Classes/Generated/BPKColor.h
Backpack/Color/Classes/Generated/BPKColor.m
Backpack/Color/Classes/Generated/UIColor+Backpack.h
package-lock.json
package.json

Updates bpk-foundations-ios to adopt the latest changes
+ [ ] Tests

[NO JIRA]: Updating foundations to the latest

---

Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarSelectionHandler.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarSelectionHandler.swift
Backpack-SwiftUI/Calendar/README.md
Example/Backpack.xcodeproj/project.pbxproj

Goal is to give a flexibility to consumers to adapt the date selection handling mechanism.
It should be necessary if we want to change the behaviour of selecting date ranges, for example (is selected date should be a departure or return date, for example).
More details is here: https://skyscanner.atlassian.net/browse/DON-1067
+ [ ] Tests …

DON-1067: Change calendar selection behaviour

---

Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
Backpack-SwiftUI/BottomSheet/Classes/KeyboardAvoidingViewModifier.swift

**Problem:**
When` bpkBottomSheet`'s content mode is `.fitMode`, the expectation is that the sheet will take the intrinsic height of its content, expanding and collapsing as the content changes, and to activate scrolling once the content exceed the maximum sheet height. But the `ContentFitBottomSheet`  implementation doesn't place its content in a scrollView, it's the consumer responsibility to do so. But when a consumer wraps their content in a scrollview, the sheet doesn't appear.
https://github.com/user-attachments/assets/60ae4bdb-95ae-4b65-abe7-a690ba5e6482
+ [ ] Tests
+ [ ] …

AI-1071: Fix ContentFitBottomSheet

---

Backpack-SwiftUI/Calendar/Classes/CalendarHeader.swift
Backpack-SwiftUI/Calendar/Classes/Core/CalendarMonthGrid.swift
Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
Backpack-SwiftUI/Calendar/Classes/Single/SingleCalendarContainer.swift

There are two potential accessibility issues:
1. Apparently, if there is a higher level .accessibilityHidden() modifier, it would override everything for children
In the DateSelector case we added this for the Cheapest month, this harmless modifier affects everything inside. But this header always should be hidden for accessibility. The easiest workaround it to override its accessibility behaviour.
2. Because of the complex structure of the day and accessory view cells, there is a major accessibility issue when a day view is separately from an accessory view. It makes a lot of confusion for accessibility users. So, we had to combine its content. (small note about a button trait, it had to be placed into a different part as it affected accessibility view's structure). …

DON-1275: Fix bpkcalendar accessibility

---

Backpack-SwiftUI/Button/Classes/BPKCloseButton.swift

Fix the issue where the close button is not accessible in `BPKAppSearchModal` on iOS 16.
The core issue stems from the following SwiftUI initializer:
[Image.init(decorative:bundle:)](https://developer.apple.com/documentation/swiftui/image/init(decorative:bundle:))
And its usage in the codebase:
[BPKIconView.swift#L89](https://github.com/Skyscanner/backpack-ios/blob/main/Backpack-SwiftUI/Icons/Classes/BPKIconView.swift#L89)
Yes — the issue appears to affect only iOS 16. You can verify this using the Accessibility Inspector on the Close Button in the `BPKAppSearchModal`:
On iOS 16, the close button is not visible to assistive technologies.
On iOS 18, it behaves as expected.
While there’s no official documentation, it seems due to enhancements in the SwiftUI accessibility tree in iOS 17+. …

[DON-1248] Update BPKCloseButton for fix accessibility issue in iOS 16

---

Backpack-SwiftUI/Font/Classes/BPKFont.swift

- Adds static methods for `black` weight font creation
+ [ ] Tests

[INC-2367] Static methods for fonts on iOS

---

Backpack-SwiftUI/Button/Classes/UIView+SwiftUIButton.swift

Ticket: [DON-1949](https://skyscanner.atlassian.net/browse/DON-1949)
Move identifier to actual BPKButton not the hosting view
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CODE_REVIEW_GUIDELINES.m …

DON-1949 Accessibility Identifier on BPKButton not Hosting view

---

Backpack-SwiftUI/Button/Classes/UIView+SwiftUIButton.swift

Ticket: [DON-1953](https://skyscanner.atlassian.net/browse/DON-1953)
Add warning label to wrapper
+ [ ] Tests
[DON-1953]: …

DON-1953 add warning label to BPKButton wrapper

---

Backpack-SwiftUI/Calendar/Classes/Core/CalendarContainer.swift

Fix accessibility where last day of the week can't be selected in calendar
Following this conversation with designers it has been decided to add a padding around the calendar when voice over is activated to prevent the scroll bar to cover the activation point of the right side dates: https://skyscanner.slack.com/archives/C07LH0LRCAK/p1758121883831479
+ [ ] Tests …

DON-2091 Fix accessibility 
