Skyscanner/backpack-ios

- .travis.yml
Fixes https://github.com/Skyscanner/backpack-ios/issues/5
> [BPK-1206] Whitelist greenkeeper branch

- .eslintignore
- .eslintrc
- .prettierrc
- Example/Podfile.lock
- gulpfile.js
- package-lock.json
- package.json
Having some issues getting `lint-staged` to run `eslint` when committing a modified `.js` file. Apart from that, this should be ready to ship!
> [BPK-1261] Add eslint config to backpack-ios

- Backpack.podspec
- Backpack/Classes/Radii/Generated/BPKRadii.h
- Backpack/Classes/Radii/Generated/BPKRadii.m
- Backpack/Classes/Radii/Radii.h
- CHANGELOG.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/View Controllers/BPKRadiiViewController.h
- Example/Backpack/View Controllers/BPKRadiiViewController.m
- Example/Podfile.lock
- Example/Tests/BPKRadiiTest.m
- README.md
- gulpfile.js
- templates/BPKRadii.h.njk
- templates/BPKRadii.m.njk
> [BPK-1253] Add BPKRadii values

- Backpack.podspec
- Backpack/Classes/Shadow/Generated/BPKShadow.h
- Backpack/Classes/Shadow/Generated/BPKShadow.m
- Backpack/Classes/Shadow/Shadow.h
- CHANGELOG.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/View Controllers/BPKShadowViewController.h
- Example/Backpack/View Controllers/BPKShadowViewController.m
- Example/Podfile
- Example/Podfile.lock
- Example/Tests/BPKShadowTest.m
- README.md
- gulpfile.js
- package-lock.json
- package.json
- templates/BPKShadow.h.njk
- templates/BPKShadow.m.njk
> Bpk 1247 add shadow tokens

- .eslintrc
- gulpfile.js
- package-lock.json
- package.json
Use the new `eslint-config-skyscanner-with-prettier`.
> [BPK-1671] Integrate prettier

- Backpack.podspec
- Backpack/Classes/Font/Generated/BPKFont.h
- Backpack/Classes/Label/BPKLabel.h
- Backpack/Classes/Label/BPKLabel.m
- Backpack/Classes/Label/Label.h
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Localizable.strings
- Example/Backpack/View Controllers/BPKBadgesViewController.h
- Example/Backpack/View Controllers/BPKBadgesViewController.m
- Example/Backpack/View Controllers/BPKFontsViewController.m
- Example/Backpack/View Controllers/BPKRootListTableViewController.h
- Example/Backpack/View Controllers/BPKRootListTableViewController.m
- Example/Podfile.lock
- Example/Tests/BPKBadgeTest.m
- Example/Tests/BPKFontTest.m
- Example/Tests/BPKGradientTest.m
- Example/Tests/BPKLabelTest.m
- Example/Tests/BPKPanelTest.m
- gulpfile.js
- templates/BPKFont.h.njk
> [BPK-1844] Implement BPKLabel

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- UNRELEASED.md
- decisions/README.md
- decisions/TEMPLATE.md
Just some consistency improvement with the monorepo
> [NoJira] improve consistency with the monorepo

- Backpack/Icon/Classes/BPKIcon.h
- Backpack/Icon/Classes/BPKIcon.m
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/View Controllers/ColorsViewController.swift
- Example/Backpack/View Controllers/IconsViewController.swift
- Example/Backpack/Views/CollectionView Cells/IconsPreviewCollectionViewCell.swift
- Example/Backpack/Views/CollectionView Headers/PreviewCollectionViewHeader.swift
- UNRELEASED.md
> [BPK-1934] Add icon story

- Backpack.podspec
- Backpack/Card/Classes/BPKCard.h
- Backpack/Card/Classes/BPKCard.m
- Backpack/Card/Classes/Card.h
- Backpack/Card/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Cards.storyboard
- Example/Backpack/View Controllers/CardsSelectorViewController.swift
- Example/Backpack/View Controllers/CardsViewController.swift
- Example/Podfile.lock
- UNRELEASED.md
> [BPK-1960] Add card component

- Backpack/Card/Classes/BPKCardDivider.h
- Backpack/Card/Classes/BPKCardDivider.m
- Backpack/Card/Classes/BPKDividedCard.h
- Backpack/Card/Classes/BPKDividedCard.m
- Backpack/Card/Classes/Card.h
- Backpack/Card/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Cards.storyboard
- Example/Backpack/View Controllers/CardsSelectorViewController.swift
- Example/Backpack/View Controllers/CardsViewController.swift
- Example/Backpack/View Controllers/DividedCardsViewController.swift
- UNRELEASED.md
> [BPK-1960] add divided card styles

- Backpack/Badge/Classes/BPKBadge.h
- Backpack/Card/Classes/BPKDividedCard.h
- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Font/Classes/Generated/BPKFont.h
- Backpack/Gradient/Classes/BPKGradientLayer.h
- Backpack/Panel/Classes/BPKPanel.h
- Example/Backpack/View Controllers/DividedCardsViewController.swift
- UNRELEASED.md
- templates/BPKColor.h.njk
- templates/BPKFont.h.njk
**Once this is merged, we should release `backpack-ios v1.0.0`**
> [BPK-1919] Update pod API for Swift consumption

- Backpack.podspec
- Backpack/Chip/Classes/BPKChip.h
- Backpack/Chip/Classes/BPKChip.m
- Backpack/Chip/Classes/Chip.h
- Backpack/Chip/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Chips.storyboard
- Example/Backpack/View Controllers/ChipsViewController.swift
- Example/Podfile.lock
- UNRELEASED.md
> [BPK-1975] Add chip component

- Backpack/Chip/Classes/BPKChip.m
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Chips.storyboard
- Example/Backpack/View Controllers/ChipsViewController.swift
- Example/Backpack/Views/CollectionView Cells/ChipPreviewCollectionViewCell.swift
- Example/Backpack/Views/CollectionView FlowLayouts/UICollectionViewMasonryFlowLayout.swift
Update the story to align to RN.
> [BPK-1975] new chip story

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarAppearance.h
- Backpack/Calendar/Classes/BPKCalendarAppearance.m
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Calendar/Classes/BPKCalendarCell.m
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.h
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.m
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.h
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
- Backpack/Calendar/Classes/BPKCalendarYearPill.h
- Backpack/Calendar/Classes/BPKCalendarYearPill.m
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/View Controllers/CalendarViewController.swift
This pull request adds the UI for range selection
> [Stark-1652] Add range selection feature

- Rakefile
https://github.com/Skyscanner/backpack-android/pull/129/files
> [No JIRA] Add npm ci to release task

- UNRELEASED.md
> [BPK-2126] Update UNRELEASED.md

- Backpack/Font/Classes/Generated/BPKFont.h
- Backpack/Font/Classes/Generated/BPKFont.m
- Example/Tests/BPKFontTest.m
- templates/BPKFont.h.njk
- templates/BPKFont.m.njk
Add new method to construct attributes with supplied custom attributes
easily.
> [No JIRA] Improve BPKFont API

- Backpack/Button/Classes/BPKButton.m
- UNRELEASED.md
Setting title after disabling the button causes the attributed to be set with the wrong text color.
I have modified `currentContentColor` to return the disabled content color if disabled.
I have also changed the background color for disabled link buttons as it should be invisible, but was white.
> [NO-JIRA] Fix button disabled style

- .github/pull_request_template.md
- CODE_REVIEW_GUIDELINES.md
- CONTRIBUTING.md
+ [x] Check this if you have read and followed the [Contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/master/CONTRIBUTING.md)
> [No JIRA] Add code review guidelines

- Backpack/Theme/Classes/BPKHongKongTheme.h
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKHongKongThemeContainer.h
- Backpack/Theme/Classes/BPKHongKongThemeContainer.m
- Backpack/Theme/Classes/BPKLondonTheme.h
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKLondonThemeContainer.h
- Backpack/Theme/Classes/BPKLondonThemeContainer.m
- Backpack/Theme/Classes/Theme.h
- Backpack/Theme/README.md
This PR is just here to help avoid creating one huge one. No visual change in this one, but you can test it out (if you really want to) by following the added `README.md`
> [BPK-2245] Add Backpack themes

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Settings.storyboard
- Example/Backpack/ShakeableWindow.h
- Example/Backpack/ShakeableWindow.m
- Example/Backpack/View Controllers/BPKRootListTableViewController.m
- Example/Backpack/View Controllers/SettingsViewController.swift
> [BPK-2245] Add settings view to Example app

- Example/Backpack/View Controllers/BPKButtonSelectorViewController.h
- Example/Backpack/View Controllers/BPKButtonSelectorViewController.m
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/Backpack/View Controllers/GradientSelectorTableViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- Example/SnapshotTests/BPKCalendarYearPill.m
- Example/Tests/BPKIconTest.m
- Example/Tests/IconSwiftTest.swift
Approved in https://github.com/Skyscanner/backpack-ios/pull/192
> [NO-JIRA] License header fixes - second pass

- CONTRIBUTING.md
> [No JIRA] Fix Code Review Guidelines link

- Backpack/Theme/Classes/BPKDohaTheme.h
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKDohaThemeContainer.h
- Backpack/Theme/Classes/BPKDohaThemeContainer.m
> [NO-JIRA] Add Doha theme

- Rakefile
Results from a similar approach I took using JS
| Attempt | Result |
| ----- | ----- |
| 1 | Passed (1st attempt) |
| 2 | Passed (1st attempt) |
| 3 | Passed (1st attempt) |
| 4 | Passed (1st attempt) |
| 5 | Passed (1st attempt) |
| 6 | Passed (1st attempt) |
| 7 | Passed (1st attempt) |
| 8 | Passed (**2nd** attempt) |
| 9 | Passed (**2nd** attempt) |
| 10 | Passed (1st attempt) |
| 11 | Passed (1st attempt) |
> [NO-JIRA] Repeat failing tests on CI

- Backpack/Theme/Classes/BPKDohaTheme.h
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.h
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/Theme.h
> [NO-JIRA] Refactor theme classes

- Rakefile
> [NO-JIRA] Prevent device erasing on release

- Rakefile
> Third time lucky

- Backpack/Theme/README.md
> [NO-JIRA] Fix theming readme

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKSimpleDate.h
- Backpack/Calendar/Classes/BPKSimpleDate.m
- Backpack/Calendar/Classes/Calendar.h
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
Reverts Skyscanner/backpack-ios#203
> Revert "Introducing SimpleDate in BPKCalendar"

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKSimpleDate.h
- Backpack/Calendar/Classes/BPKSimpleDate.m
- Backpack/Calendar/Classes/Calendar.h
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
Reverts Skyscanner/backpack-ios#214
> Revert "Revert "Introducing SimpleDate in BPKCalendar""

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Example/Backpack/View Controllers/CalendarViewController.swift
- UNRELEASED.md
The API was in fact incorrect with regards to the nullaiblity of the new
methods.
> [No JIRA] Ensure BPKCalendar API is Swifty

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKThemeContainerController.m
- Example/Utils/StorageHelpers.swift
- Example/Utils/ThemingHelpers.swift
> [BPK-2339] Add theme setting helpers

- Backpack/Theme/Classes/BPKDefaultTheme.h
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDefaultThemeContainer.h
- Backpack/Theme/Classes/BPKDefaultThemeContainer.m
- Backpack/Theme/Classes/BPKDohaTheme.h
- Backpack/Theme/Classes/BPKHongKongTheme.h
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.h
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- Backpack/Theme/Classes/Theme.h
- Backpack/Theme/README.md
- Example/Backpack/BPKAppDelegate.m
- UNRELEASED.md
> Add default theme

- package-lock.json
- package.json
> Greenkeeper/bpk svgs 6.4.2

- Example/Backpack/BPKExampleApp.swift
> [BPK-2339] Prevent duplicate showing of settings screen

- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeContainerController.m
> [BPK-2339] Add notification observer to TCC

- .travis.yml
- Example/.swiftlint.yml
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/ExampleApp.swift
- Example/Backpack/View Controllers/BPKRootListTableViewController.m
- Example/Backpack/View Controllers/IconsViewController.swift
- Example/Backpack/View Controllers/SettingsViewController.swift
- Example/Backpack/main.m
- Example/Podfile
- Example/Podfile.lock
- Example/Utils/ThemeHelpers.swift
Full list of rules [here](https://github.com/realm/SwiftLint/blob/master/Rules.md)
> [No JIRA] Opt in to a few more swiftlint rules

- Backpack/Dialog/Classes/BPKDialogScrimAction.h
> [NO-JIRA] Fix dialog scrim nullables

- Backpack/Spinner/Classes/BPKSpinner.h
- Backpack/Spinner/Classes/BPKSpinner.m
- Backpack/Spinner/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> [BPK-2327] Add spinner theming

- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/Theme.h
> [NO-JIRA] Fix theme imports

- Backpack/Dialog/Classes/BPKDialogButtonAction.h
- Backpack/Gradient/Classes/BPKGradient.h
- Backpack/Label/Classes/BPKLabel.h
- Backpack/Radii/Classes/Generated/BPKRadii.h
- Backpack/TextView/Classes/BPKTextView.h
- Rakefile
- templates/BPKRadii.h.njk
> [No JIRA] Fix docs build

- Rakefile
> [Rake] Ensure git has fetched before release

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Settings.storyboard
- Example/Backpack/View Controllers/SettingsViewController.swift
- Example/Backpack/Views/BPKTableViewSelectableCell.swift
> [BPK-2339] implement switch theming

- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> [BPK-2270] Add primary color to theme definitions

- Backpack/Theme/Classes/BPKDefaultThemeContainer.h
- Backpack/Theme/Classes/BPKDohaThemeContainer.m
- Backpack/Theme/Classes/BPKHongKongThemeContainer.m
- Backpack/Theme/Classes/BPKLondonThemeContainer.m
- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeContainerController.m
> [BPK-2270] Clean up Theme Container classes

- Backpack/Button/Classes/BPKButton.m
- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- Backpack/Color/README.md
- UNRELEASED.md
- templates/BPKColor.h.njk
- templates/BPKColor.m.njk
Add colour mixing utility for blending two colours together at a specified percentage.
> [BPK-2386] Add colour mixing utility

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Backpack/Button/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
Waiting on https://github.com/Skyscanner/backpack-ios/pull/261
> [BPK-2321] Add primary button theme support

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- templates/BPKColor.h.njk
- templates/BPKColor.m.njk
> [NO-JIRA] Fix color code formatting

- Backpack/Theme/Classes/BPKThemeContainer.h
> [NO-JIRA] Remove dead code

- .spelling
- Example/Backpack/View Controllers/GradientSelectorTableViewController.swift
> [NO-JIRA] Enable distribution build

- Backpack/Switch/Classes/BPKSwitch.h
- Backpack/Switch/Classes/BPKSwitch.m
- Backpack/Theme/Classes/BPKTheme.m
- UNRELEASED.md
> [BPK-2320] Fix race condition in Switch theming

- Backpack/Chip/Classes/BPKChip.h
- Backpack/Chip/Classes/BPKChip.m
- Backpack/Switch/Classes/BPKSwitch.h
- Backpack/Switch/Classes/BPKSwitch.m
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> [BPK-2380] Add theming support to chip

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Backpack/Button/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- CHANGELOG.md
- UNRELEASED.md
> [BPK-2402] Add theme support to button link

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> [BPK-2328] Add theming support to calendar

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
<details>
<summary>London</summary>
</details>
<details>
<summary>Doha</summary>
</details>
<details>
<summary>Hong Kong</summary>
</details>
> [BPK-2413] Add support for corner radius theming in Button

- Gemfile.lock
> [No JIRA] Update jazzy version

- .clang-format
> [NO-JIRA] Remove spaces in litterals

- Backpack/Button/Classes/BPKButton.m
- UNRELEASED.md
> [BPK-2102] Fix button heights and font weight

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarCell.m
Added `Button`, `NotEnabled` and `Selected` attributes as appropriate
> [BPK-2484] BPK Calendar A11y improvements

- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKSilverTheme.m
- Backpack/Theme/Classes/BPKTheme.h
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- Backpack/Theme/README.md
- Example/Backpack/View Controllers/ColorsViewController.swift
- UNRELEASED.md
> [BPK-2480] Gray theming utility

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Backpack/Button/README.md
- Backpack/Theme/Classes/BPKTheme.m
> [BPK-2326] Implement font theming for button

- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Buttons.storyboard
- Example/Backpack/Cards.storyboard
- Example/Backpack/Dialogs.storyboard
- Example/Backpack/Settings.storyboard
> [NO-JIRA] backpackify-all-the-labels

- Example/Backpack/Base.lproj/Main.storyboard
> [NO-JIRA] Backpackify remaining labels

- Backpack/TextView/Classes/BPKTextView.h
- Backpack/TextView/Classes/BPKTextView.m
- Backpack/TextView/README.md
- Backpack/Theme/Classes/BPKTheme.m
> [BPK-2556] Add font theming support to text view

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Calendar/Classes/BPKCalendarCell.m
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.h
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.m
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.h
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
- Backpack/Calendar/Classes/BPKCalendarYearPill.h
- Backpack/Calendar/Classes/BPKCalendarYearPill.m
- Backpack/Calendar/Classes/Calendar.h
- Backpack/Calendar/README.md
- Backpack/Theme/Classes/BPKTheme.m
> [BPK-2326] implement font theming for calendar

- Rakefile
> [No JIRA] Support custom versions [ci-skip]

- Backpack/Theme/Classes/BPKTheme.m
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/View Controllers/ColorsViewController.swift
- Example/Backpack/Views/BPKBadgeContainer.swift
- Example/Backpack/Views/BPKTableViewSelectableCell.swift
- Example/Backpack/Views/CollectionView Cells/ColorPreviewCollectionViewCell.swift
- Example/Utils/ThemeHelpers.swift
- Example/Utils/ThemeRegistry.swift
- UNRELEASED.md
All usages in the apps codebase have been removed already 👍 
> [NO-JIRA] Deprecate gray utilities

- Backpack/Font/Classes/Generated/BPKFont.h
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/View Controllers/TextFieldsViewController.swift
- templates/BPKFont.h.njk
> [BPK-2557] Text field fixes

- Backpack.podspec
- Example/Podfile.lock
- Rakefile
> [BPK-2596] Add TTTAttributedLabel dependency

- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.h
- Backpack/TappableLinkLabel/README.md
> [BPK-2569] Improve BPKTappableLinkLabel docs

- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.h
- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- Example/Backpack/View Controllers/TappableLinkLabelsViewController.swift
> [BPK-2596] Add proxy for number of lines

- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabelDelegate.h
- Backpack/TappableLinkLabel/README.md
- Example/Backpack/View Controllers/TappableLinkLabelsViewController.swift
+ [-] `UNRELEASED.md`
+ [-] Tests
+ [-] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)
> [BPK-2596] Fix Tappable Label protocol naming

- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
+ [ ] ~`UNRELEASED.md`~
+ [ ] ~`README.md`~
+ [x] Tests
+ [ ] ~Docs~
> Swap london and hong kong fonts

- Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native
+ [ ] ~`UNRELEASED.md`~
+ [ ] ~`README.md`~
+ [ ] ~Tests~
+ [ ] ~Docs~
> [BPK-2696] Add RTL profile

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Calendar/Classes/BPKCalendarCell.m
- UNRELEASED.md
+ [ ] ~`README.md`~
+ [ ] ~Tests~
+ [ ] ~Docs~
> [NO-JIRA] Fix calendar RTL

- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.h
- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- UNRELEASED.md
> [NO-JIRA] Adding textAlignment and lineBreakMode to BPKTappableLinkLable

- Backpack/Dialog/Classes/BPKDialogController.m
- Backpack/Dialog/Classes/BPKDialogControllerAnimator.m
- UNRELEASED.md
> Make dialog respect reduced transparency and reduced motion

- Backpack/StarRating/Classes/BPKStarRating.h
> [No JIRA] Make sure star rating shows up in docs

- Backpack/Badge/Classes/BPKBadge.m
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarAppearance.h
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Calendar/Classes/BPKCalendarCell.m
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.h
- Backpack/Calendar/Classes/BPKCalendarHeaderCell.m
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.h
- Backpack/Calendar/Classes/BPKCalendarStickyHeader.m
- Backpack/Calendar/Classes/BPKCalendarYearPill.h
- Backpack/Calendar/Classes/BPKCalendarYearPill.m
- Backpack/Card/Classes/BPKCard.h
- Backpack/Card/Classes/BPKCardDivider.h
- Backpack/Card/Classes/BPKDividedCard.h
- Backpack/Card/Classes/BPKDividedCard.m
- Backpack/Dialog/Classes/BPKDialogButtonAction.h
- Backpack/Dialog/Classes/BPKDialogButtonAction.m
- Backpack/Dialog/Classes/BPKDialogController.m
- Backpack/Dialog/Classes/BPKDialogView.m
- Backpack/Font/Classes/BPKFontMapping.m
- Backpack/Font/Classes/Generated/BPKFont.m
- Backpack/Gradient/Classes/BPKGradient.m
- Backpack/Gradient/Classes/BPKGradientLayer.h
- Backpack/Gradient/Classes/BPKGradientView.m
- Backpack/Gradient/Classes/BPKPrimaryGradientView.m
- Backpack/Icon/Classes/BPKIcon.h
- Backpack/Icon/Classes/BPKIconView.m
- decisions/import-ordering.md
- templates/BPKFont.m.njk
> Add decision about import ordering

- .spelling
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationDelegate.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItem.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItem.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.m
- Backpack/HorizontalNavigation/Classes/HorizontalNavigation.h
- Backpack/HorizontalNavigation/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKSilverTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/HorizontalNavigation.storyboard
- Example/Backpack/TappableLinkLabels.storyboard
- Example/Backpack/View Controllers/HorizontalNavSelectorViewController.swift
- Example/Backpack/View Controllers/HorizontalNavViewController.swift
- Example/Backpack/View Controllers/TappableLinkLabelsSelectorViewController.swift
- UNRELEASED.md
+ [ ] Tests
Follow up PR's to add:
> [BPK-2460] Add Horizontal Navigation component

- .travis.yml
- Rakefile
> [NO-JIRA] Enforce clang in CI

- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationDelegate.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItem.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItem.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.m
- Backpack/HorizontalNavigation/README.md
- Example/Backpack/View Controllers/HorizontalNavViewController.swift
- Example/SnapshotTests/BPKHorizontalNavigationSnapshotTest.m
- Example/Tests/BPKHorizontalNavigationTest.m
- UNRELEASED.md
> Add tag property to horizontal navigation

- Backpack/Dialog/README.md
> Fix dialog readme

- Backpack/Font/Classes/BPKFontMapping.m
- UNRELEASED.md
> [NO-JIRA] Fix font mapping logic

- Backpack/Calendar/README.md
> [BPK-2182] Add calendar README usage instructions

- .spelling
- Backpack/NavigationBar/Classes/BPKNavigationBar.h
- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- Backpack/NavigationBar/Classes/BPKNavigationBarLargeTitleView.h
- Backpack/NavigationBar/Classes/BPKNavigationBarLargeTitleView.m
- Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.h
- Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.m
- Backpack/NavigationBar/Classes/NavigationBar.h
- Backpack/NavigationBar/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/NavigationBar.storyboard
- Example/Backpack/View Controllers/NavigationBarViewController.swift
+ [ ] Ensure it works on iOS 10.
+ [ ] Expose large title tint color.
+ [ ] Support custom layout margins for larege title.
+ [ ] Add Tests.
+ [ ] Add Docs.
+ [ ] Tests …
> [BPK-2807] Implement large title Navigation bar

- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKSilverTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> Add system red and system green to BPKThemeDefinition

- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
> Update theme grays as gray theming will be deprecated

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- UNRELEASED.md
- package-lock.json
- package.json
> Update bpk dependencies

- Rakefile
> Change default build SDK to support XCode 10.2.1

- Backpack/NavigationBar/Classes/BPKNavigationBar.h
- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- Backpack/NavigationBar/Classes/BPKNavigationBarLargeTitleView.h
- Backpack/NavigationBar/Classes/BPKNavigationBarLargeTitleView.m
- Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.h
- Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.m
- Backpack/NavigationBar/Classes/NavigationBar.h
- CHANGELOG.md
Think we should revert this change as it turns out I fixed nothing 😆 
+ [x] Tests
> Revert Georges non-fix

- Backpack/Button/Classes/BPKButton.m
- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- Backpack/NavigationBar/Classes/BPKNavigationBarTitleView.m
- Example/SnapshotTests/BPKGradientSnapshotTests.m
- Example/SnapshotTests/BPKHorizontalNavigationSnapshotTest.m
- Example/SnapshotTests/BPKNavigationBarSnapshotTest.m
- Example/SnapshotTests/BPKProgressBarSnapshotTest.m
- Example/Tests/BPKGradientTest.m
> Dogfood colours

- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- Example/Backpack/Base.lproj/Main.storyboard
> [NO-JIRA] fix panel segue

- Backpack/NavigationBar/Classes/BPKNavigationBar.h
- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- Backpack/NavigationBar/README.md
- Example/Backpack/View Controllers/NavigationBarViewController.swift
- UNRELEASED.md
> [BPK-2863] Spring navigation titles into view

- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- UNRELEASED.md
> baseOffset fix for navigation bar

- Rakefile
> [NO-JIRA] CI improvements

- Rakefile
> [NO-JIRA] Update default SDK

- Backpack/Rating/Classes/BPKRating.h
- Backpack/Rating/Classes/BPKRating.m
- Backpack/Rating/Classes/BPKRatingBubble.h
- Backpack/Rating/Classes/BPKRatingBubble.m
- Backpack/Rating/Classes/BPKRatingTextDefinition.h
- Backpack/Rating/Classes/BPKRatingTextDefinition.m
- Backpack/Rating/README.md
- Example/Backpack/View Controllers/RatingsViewController.swift
- Example/Podfile.lock
- Example/SnapshotTests/BPKRatingSnapshotTest.m
> API changes in Rating component

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKAppDelegate.m
- Example/Podfile
- Example/Podfile.lock
> [NO-JIRA] Integrate app center

- Backpack/FlareView/Classes/BPKFlarePath.m
- Example/Backpack/FlareView.storyboard
- Example/Backpack/View Controllers/FlareViewSelectorViewController.swift
- Example/Backpack/View Controllers/FlareViewViewController.swift
- UNRELEASED.md
> [BPK-3031] Fix flare mask crack

- Backpack/Backpack.h
- Backpack/Duration/Classes/Duration.h
- Backpack/Duration/Classes/Generated/BPKDuration.h
- Backpack/Duration/Classes/Generated/BPKDuration.m
- Backpack/Duration/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Tests/BPKDurationTest.m
- UNRELEASED.md
- gulpfile.js
- templates/BPKDuration.h.njk
- templates/BPKDuration.m.njk
> [BPK-3033] Add Backpack Durations

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Backpack Native-Bridging-Header.h
- Example/Backpack/View Controllers/BPKButtonsViewController.m
- Example/Backpack/View Controllers/TappableLinkLabelsViewController.swift
- Example/Utils/BPKExampleAppTitleAttributes.h
- Example/Utils/BPKExampleAppTitleAttributes.m
> [NO-JIRA] Fix XCode 9 text attributes

- Backpack.podspec
- Example/Podfile.lock
> [NO-JIRA] Update podfile lock

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- Backpack/Font/Classes/Generated/BPKFont.m
- Backpack/Label/Classes/BPKLabel.m
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/Labels.storyboard
- Example/Backpack/View Controllers/BPKDarkModeTableViewController.m
- Example/Tests/BPKLabelTest.m
- Example/Utils/ThemeHelpers.swift
- templates/BPKColor.h.njk
- templates/BPKColor.m.njk
- templates/BPKFont.m.njk
> Initial refactor to support dark mode

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- Example/Backpack/View Controllers/ColorsViewController.swift
- UNRELEASED.md
- templates/BPKColor.h.njk
- templates/BPKColor.m.njk
> New background color

- .spelling
- Backpack/Backpack.h
- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/README.md
- Backpack/SimpleDate/Classes/BPKSimpleDate.h
- Backpack/SimpleDate/Classes/BPKSimpleDate.m
- Backpack/SimpleDate/Classes/SimpleDate.h
- Backpack/SimpleDate/README.md
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- UNRELEASED.md
> [BPK-3081] Split SimpleDate into separate import

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- Backpack/Font/Classes/Generated/BPKFont.m
- Backpack/Label/Classes/BPKLabel.m
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/Backpack Native-Bridging-Header.h
- Example/Tests/BPKLabelTest.m
- gulpfile.js
- templates/BPKColor.h.njk
- templates/BPKColor.m.njk
- templates/BPKFont.m.njk
> [BPK-3098] Generate dynamic colours from tokens

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- package-lock.json
- package.json
> [NO-JIRA] Update bpk-tokens

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- package-lock.json
- package.json
> [NO-JIRA] Upgrade bpk-tokens

- Example/Backpack/View Controllers/ColorsViewController.swift
> [NO-JIRA] Showcase more colours

- Backpack/Spinner/Classes/BPKSpinner.m
- Backpack/Switch/Classes/BPKSwitch.m
- UNRELEASED.md
> [NO-JIRA] Switch spinner dark mode

- Backpack/Dialog/Classes/BPKDialogController.m
- Backpack/Dialog/Classes/BPKDialogIconView.m
- Backpack/Dialog/Classes/BPKDialogView.m
- UNRELEASED.md
> Fix Dialog on dark mode

- Backpack/Card/Classes/BPKCard.m
- Backpack/Panel/Classes/BPKPanel.m
- Example/Backpack/View Controllers/CardsViewController.swift
> [NO-JIRA] Fix DM for card and panel

- Backpack/Rating/Classes/BPKRatingTextWrapper.m
> [NO-JIRA] Fix rating subtitles

- Backpack/TextField/Classes/BPKTextField.m
- UNRELEASED.md
> fix text field on dark mode

- Backpack/Icon/Classes/BPKIconView.m
> [BPK-3121] Icon dark mode support

- Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
- Example/Backpack/View Controllers/Bottom Sheet/BottomSheetViewController.swift
> [BPK-3116] Support dark mode in bottom sheet

- Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
- Backpack/Button/Classes/BPKButton.m
> [NO-JIRA] Fix CI

- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItem.m
- Backpack/ProgressBar/Classes/BPKProgressBar.m
- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKHongKongTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Backpack/Theme/Classes/BPKSilverTheme.m
- Backpack/Theme/Classes/BPKSpringCleanTheme.m
- Backpack/Theme/Classes/BPKTheme.m
- Backpack/Theme/Classes/BPKThemeDefinition.h
- UNRELEASED.md
> [NO-JIRA] Remaining theme refactoring

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/SimpleDate/Classes/BPKSimpleDate.h
- Backpack/SimpleDate/Classes/BPKSimpleDate.m
- Backpack/SimpleDate/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- Example/Tests/BPKSimpleDateTest.m
- UNRELEASED.md
> [BPK-3194] Simple date from Calendar

- Backpack/Button/Classes/BPKButton.m
- UNRELEASED.md
> [BPK-3262] Fix button change on trait collection change

- Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native override interface style.xcscheme
- Example/Backpack/View Controllers/BPKButtonsViewController.m
- Example/Utils/ThemeHelpers.swift
> [BPK-3266] Add schema for testing userInterfaceStyle overrides

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Example/Backpack/View Controllers/BPKButtonsViewController.m
- UNRELEASED.md
See the explaination added to `BPKButton.m`
+ [x] Tests
> [BPK-3266] fix button interfacestyle overridden

- Backpack/Dialog/Classes/BPKDialogView.m
- UNRELEASED.md
> [NO-JIRA] Fix ios 11 flareview bug

- Backpack/Button/Classes/BPKButton.m
- UNRELEASED.md
> [BPK-3290] Fix Button interaction with title set nil

- Example/Backpack/Base.lproj/Main.storyboard
> [NO-JIRA] Fix Bottom sheet label alignment

- Backpack/Color/Classes/Generated/BPKColor.h
- gulpfile.js
- templates/BPKColor.h.njk
> [NO-JIRA] Add RGB values to Color definitions

- Backpack/Calendar/Classes/BPKCalendar.m
- UNRELEASED.md
> [BPK-3075] Hide disabled dates from screenreader

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/Calendar.storyboard
- Example/Backpack/View Controllers/CalendarSelectorViewController.swift
Small one just to set up the storyboard for the new Calendar config because no one likes resolving .storyboard merge conflicts 😆 
+ NA `UNRELEASED.md`
+ NA `README.md`
+ NA Tests
+ NA Adding a component? Remember to expose it in the [main `Backpack.h` header file](https://github.com/Skyscanner/backpack-ios/tree/master/Backpack/Backpack.h)
+ NA Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/master/CODE_ …
> [BPK-3075] Add calendar selector view controller

- Rakefile
> [BPK-3321] Output changed files

- Backpack/FlareView/Classes/BPKFlareView.m
- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- Backpack/Rating/Classes/BPKRatingBubble.m
- Backpack/Rating/Classes/BPKRatingTextWrapper.m
- Backpack/SimpleDate/Classes/BPKSimpleDate.h
- Backpack/SimpleDate/Classes/BPKSimpleDate.m
- Backpack/Switch/Classes/BPKSwitch.m
- Backpack/TappableLinkLabel/Classes/BPKTappableLinkLabel.m
- Example/Backpack/View Controllers/BPKButtonsViewController.m
- Example/SnapshotTests/BPKButtonSnapshotTest.m
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- Example/SnapshotTests/BPKSnapshotTest.h
- Example/Tests/BPKSimpleDateTest.m
> [BPK-3321] Fix code formatting

- Backpack/NavigationBar/Classes/BPKNavigationBar.m
- UNRELEASED.md
> [BPK-3183] Fix nav bar RTL

- Backpack/Font/Classes/Generated/BPKFont.m
- templates/BPKFont.m.njk
+ [x] `UNRELEASED.md` - Will be covered in https://github.com/Skyscanner/backpack-ios/pull/527
+ [x] Tests
> [BPK-3279] Remove unused fontForStyle

- Example/Backpack/Views/CollectionView Cells/ColorPreviewCollectionViewCell.swift
> [NO-JIRA] Ensure color names are fully visible

- Backpack/Button/Classes/BPKButton.h
- Backpack/Button/Classes/BPKButton.m
- Backpack/Theme/Classes/BPKTheme.m
- Example/Podfile.lock
- Example/SnapshotTests/BPKButtonSnapshotTest.m
- UNRELEASED.md
> BPKButton corner radius refactor

- .spelling
- Backpack/Backpack.h
- Backpack/BorderSize/Classes/BorderSize.h
- Backpack/BorderSize/Classes/Generated/BPKBorderSize.h
- Backpack/BorderSize/Classes/Generated/BPKBorderSize.m
- Backpack/BorderSize/README.md
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.m
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Tests/BPKBorderSizeTest.m
- UNRELEASED.md
- gulpfile.js
- templates/BPKBorderSize.h.njk
- templates/BPKBorderSize.m.njk
MERGE AFTER https://github.com/Skyscanner/backpack-ios/pull/536
+ [x] Tests
> [BPK-3400] Add border sizes

- Backpack/Font/Classes/BPKFontDefinitionProtocol.h
- Backpack/Font/Classes/BPKFontManager.h
- Backpack/Font/Classes/BPKFontManager.m
- Backpack/Font/Classes/BPKFontMapping.h
- Backpack/Font/Classes/BPKRelativeFontDefinition.h
- Backpack/Font/Classes/BPKRelativeFontDefinition.m
- Backpack/Font/Classes/Generated/BPKFont.h
- Backpack/Font/Classes/Generated/BPKFont.m
- Backpack/Font/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKAppDelegate.m
- Example/Podfile
- Example/Podfile.lock
- Example/Tests/BPKFontTest.m
- Example/Tests/BPKTestFontDefinition.h
- Example/Tests/BPKTestFontDefinition.m
- Rakefile
- UNRELEASED.md
- templates/BPKFont.h.njk
- templates/BPKFont.m.njk
> [BPK-3279] Add font manager

- .gitignore
- CONTRIBUTING.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/Backpack-Info.plist
- scripts/download-relative-fonts
> [BPK-3277] Add script for downloading fonts

- Example/Backpack/BPKAppDelegate.m
> [NO-JIRA] Fix font usage in Navigation

- Backpack/Font/Classes/BPKFontManager.m
- Backpack/Font/Classes/Generated/BPKFont.m
- UNRELEASED.md
- templates/BPKFont.m.njk
> [NO-JIRA] Fix font crash

- Example/Backpack.xcodeproj/project.pbxproj
- scripts/download-relative-fonts
> [NO-JIRA] Fix pxbproj warning

- Example/Backpack/BPKAppDelegate.m
- scripts/download-relative-fonts
> [NO-JIRA] Clean up Example app font logic

- Backpack/Badge/Classes/BPKBadge.h
- Backpack/Button/Classes/BPKButton.h
- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Card/Classes/BPKCard.h
- Backpack/Card/Classes/BPKCardCornerStyleValues.h
- Backpack/Card/Classes/BPKCardDivider.h
- Backpack/Card/Classes/BPKDividedCard.h
- Backpack/Dialog/Classes/BPKDialogButtonAction.h
- Backpack/Dialog/Classes/BPKDialogController.h
- Backpack/Dialog/Classes/BPKDialogScrimAction.h
- Backpack/Dialog/Classes/BPKDialogView.h
- Backpack/Dialog/Classes/BPKDialogViewDelegate.h
- Backpack/FlareView/Classes/BPKFlareView.h
- Backpack/Font/Classes/Generated/BPKFont.h
- Backpack/Gradient/Classes/BPKGradient.h
- Backpack/Gradient/Classes/BPKGradientView.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationDelegate.h
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationOption.h
- Backpack/Icon/Classes/BPKIcon.h
- Backpack/Icon/Classes/BPKIconView.h
- Backpack/Icon/Classes/Generated/BPKIconNames.h
- Backpack/Shadow/Classes/Generated/BPKShadow.h
- Gemfile
- Gemfile.lock
- UNRELEASED.md
- templates/BPKFont.h.njk
- templates/BPKIconNames.h.njk
- templates/BPKShadow.h.njk
> [No JIRA] Increase documentation coverage

- README.md
The list of components was often out of date and when rendered on the
reference doc site it was confusing because the links didn't work.
+ [x] Tests …
> [No JIRA] Cleanup README.md

- .travis.yml
> [NO-JIRA] bundler version check

- README.md
> [NO-JIRA] HTTPS README

- Example/Backpack/View Controllers/CalendarViewController.swift
before:
After:
This is just example code, so no need to update the changelog
+ [x] Tests
> [NO-JIRA] Fix dark mode calendar custom style example

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- UNRELEASED.md
- package-lock.json
- package.json
BPK Tokens version 26.0.0
+ [x] Tests
> BPK Tokens version bump

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- UNRELEASED.md
- package-lock.json
- package.json
> [BPK-3470]: Updated token dependency

- Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
- UNRELEASED.md
> [NO-JIRA] Fix bottom sheet shadow for apps codebase

- Example/Backpack/Backpack-Info.plist
> [NO-JIRA] Fix app-center auto updating

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- Rakefile
- UNRELEASED.md
> [BPK-3381] Expose calendar instance in delegate methods

- Rakefile
```
> rake -T
rake analyze           # Check for build-time errors and warnings
rake docs[outputDir]   # Build the static API docs
rake erase_devices     # Erase content and settings from all iPhone simulators
rake lint              # Runs clang-format on all h and m files to ensure formatting is correct
rake release           # Performs tests locally and then runs the release process
rake take_screenshots  # Takes screenshots of all components in both light and dark mode
rake test              # Run unit tests up to 3 times until they pass
```
+ [x] Tests
+ …
> [NO-JIRA] Document rake tasks

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- UNRELEASED.md
> [BPK-3642] Add API for refreshing date appearance

- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- UNRELEASED.md
- package-lock.json
- package.json
> [NO-JIRA] Upgrade backpack dependencies

- Backpack/Color/Classes/Generated/BPKColor.m
- UNRELEASED.md
- gulpfile.js
- templates/BPKColor.m.njk
> [BPK-3768] Use color properties to construct dynamic color properties

- .spelling
- Backpack/Backpack.h
- Backpack/TabBarController/Classes/BPKTabBarController.h
- Backpack/TabBarController/Classes/BPKTabBarController.m
- Backpack/TabBarController/Classes/TabBarController.h
- Backpack/TabBarController/README.md
- Example/Backpack Screenshot/Screenshots.swift
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Base.lproj/Main.storyboard
- Example/Backpack/TabBarControllers.storyboard
- UNRELEASED.md
+ [ ] Tests - In another PR
+ [ ] Docs  - In another PR
> [BPK-3795] Add BPKTabBarController

- Backpack/Badge/README.md
- Backpack/BorderSize/README.md
- Backpack/Button/README.md
- Backpack/Calendar/README.md
- Backpack/Card/README.md
- Backpack/DarkMode/README.md
- Backpack/Dialog/README.md
- Backpack/Duration/README.md
- Backpack/FlareView/README.md
- Backpack/Font/README.md
- Backpack/Gradient/README.md
- Backpack/HorizontalNavigation/README.md
- Backpack/Icon/README.md
- Backpack/Label/README.md
- Backpack/NavigationBar/README.md
- Backpack/Panel/README.md
- Backpack/ProgressBar/README.md
- Backpack/Radii/README.md
- Backpack/Shadow/README.md
- Backpack/Spacing/README.md
- Backpack/Spinner/README.md
- Backpack/StarRating/README.md
- Backpack/Switch/README.md
- Backpack/TappableLinkLabel/README.md
- Backpack/TextField/README.md
- Backpack/TextView/README.md
Merge after https://github.com/Skyscanner/backpack-ios/pull/637
> No jira fix swift readme 2

- Backpack/BottomSheet/README.md
- Backpack/Calendar/README.md
- Backpack/Dialog/README.md
- Backpack/FlareView/README.md
- Backpack/SimpleDate/README.md
- Backpack/Snackbar/README.md
- Backpack/TappableLinkLabel/README.md
- Backpack/TextField/README.md
- Backpack/TextView/README.md
- Backpack/Theme/README.md
- Backpack/Toast/README.md
> [BPK-3792] Make sure Swift README.mds are accurate

- Backpack/FlareView/Classes/BPKFlarePath.h
- Backpack/FlareView/Classes/BPKFlarePath.m
- Backpack/FlareView/Classes/BPKFlareView.h
- Backpack/FlareView/Classes/BPKFlareView.m
I'm not gonna put this in the readme or changelog because I don't think we want to encourage overriding.
> [BPK-3812] Enable overriding flare size

- .spelling
- Backpack/BottomSheet/Classes/BackpackFloatingPanelController.swift
- Backpack/BottomSheet/Classes/BottomSheet.swift
- Example/Backpack/View Controllers/Bottom Sheet/BottomSheetViewController.swift
- UNRELEASED.md
> [NO-JIRA] Rename BottomSheet in Swift

- Backpack/BarChart/Classes/BarChart.swift
- Backpack/BarChart/Classes/BarChartCollectionView.swift
- Example/Backpack/BarCharts.storyboard
- Example/Backpack/View Controllers/BarChartViewController.swift
> [BPK-3812] add bpk bar chart

- Backpack/BarChart/Classes/BarChartBar.swift
- Backpack/BarChart/Classes/BarChartCollectionView.swift
> [BPK-3812] Animate marker bar

- Backpack/BarChart/README.md
> [BPK-3812] Update README

- Rakefile
Follow-up PR to update the actual images
+ [x] Tests …
> [NO-JIRA] Update screenshotting rake task

- Example/.swiftlint.yml
- Example/Backpack/View Controllers/FlareViewViewController.swift
I added some rules, and they seem to work.
Not sure what the best way to test and document them is 🤷 
We should probably decide where their source-of-truth should exist, from which we can update the App and this repo regularly.
> [BPK-4023] Investigate custom swift-lint rules

- Example/.swiftlint.yml
> [BPK-4023] Update swiftlint rules

- Backpack/Badge/Classes/BPKBadge.m
- Backpack/BorderSize/Classes/Generated/BPKBorderSize.h
- Backpack/BorderSize/Classes/Generated/BPKBorderSize.m
- Backpack/BorderSize/README.md
- Backpack/BottomSheet/Classes/BottomSheet.swift
- Backpack/Button/Classes/BPKButton.m
- Backpack/Card/Classes/BPKCard.m
- Backpack/Dialog/Classes/BPKDialogView.m
- Backpack/FlareView/README.md
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.m
- Backpack/Panel/Classes/BPKPanel.m
- Backpack/Radii/Classes/Generated/BPKRadii.h
- Backpack/Radii/Classes/Generated/BPKRadii.m
- Backpack/Radii/README.md
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Example/Backpack/View Controllers/BPKRadiiViewController.m
- Example/Backpack/View Controllers/BPKShadowViewController.m
- Example/Backpack/View Controllers/FlareViewViewController.swift
- Example/Backpack/Views/CollectionView Cells/ColorPreviewCollectionViewCell.swift
- Example/SnapshotTests/BPKFlareViewSnapshotTest.m
- Example/Tests/BPKBorderSizeTest.m
- Example/Tests/BPKRadiiTest.m
- UNRELEASED.md
- package-lock.json
- package.json
- templates/BPKBorderSize.h.njk
> [BPK-4135] Add UIKit aligned tokens

- Backpack/Color/Classes/Generated/UIColor+Backpack.h
- Backpack/Color/Classes/Generated/UIColor+Backpack.m
- Backpack/Color/README.md
- Example/Tests/BPKColorTest.m
- UNRELEASED.md
- gulpfile.js
- templates/UIColor+Backpack.h.njk
- templates/UIColor+Backpack.m.njk
> [BPK-3819] Add Backpack's colours on UIColor

- .travis.yml
- Example/SnapshotTests/BPKSnapshotTest.h
- Rakefile
> [No JIRA] Upgrade to Xcode 11.7

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Example/Backpack/View Controllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- UNRELEASED.md
> [BPK-3692] Remove NSDate methods in BPKCalendar

- .travis.yml
- Backpack.podspec
- Backpack/BarChart/Classes/BarChartCollectionView.swift
- Backpack/BarChart/Classes/BarChartCollectionViewFlowLayout.swift
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Views/BPKBadgeContainer.swift
- Example/Podfile.lock
- Rakefile
- UNRELEASED.md
> [BPK-3963] Upgrade Swift 5

- Example/SnapshotTests/BPKSnapshotTest.h
> [NO-JIRA] Refactor test device checking logic

- Backpack/Radii/Classes/Generated/BPKRadii.h
- Backpack/Radii/Classes/Generated/BPKRadii.m
- Example/Tests/BPKRadiiTest.m
- UNRELEASED.md
- gulpfile.js
- package-lock.json
- package.json
> [BPK-4225] Adopt latest bpk-tokens

- Example/Backpack/Base.lproj/Main.storyboard
Before and after. Need I say more?
> [NO-JIRA] Clean up main storyboard

- .github/workflows/ci.yml
> [NO-JIRA] Fix deploy docs

- Backpack/Badge/Classes/BPKBadge.m
- Backpack/Button/Classes/BPKButton.m
- Backpack/Dialog/Classes/BPKDialogView.m
- Backpack/Radii/Classes/Generated/BPKRadii.m
- Backpack/Theme/Classes/BPKDefaultTheme.m
- Backpack/Theme/Classes/BPKDohaTheme.m
- Backpack/Theme/Classes/BPKLondonTheme.m
- Example/Backpack/View Controllers/BPKRadiiViewController.m
- Example/Backpack/View Controllers/BPKShadowViewController.m
- Example/Backpack/Views/CollectionView Cells/ColorPreviewCollectionViewCell.swift
- Example/Tests/BPKRadiiTest.m
- UNRELEASED.md
- package-lock.json
- package.json
For now I'm just replacing all `sm` values with `xs` to preserve the current behaviour. We can change the button design later 👍 
+ [x] Tests
_If you …
> [NO-JIRA] Upgrade bpk dependencies

- .github/workflows/ci.yml
Replaced the request to Travis with one to GitHub.
I've added `BACKPACK_DOCS_DEPLOY_TOKEN` to this repo.
> [No Jira] Trigger docs site action remotely

- .github/workflows/ci.yml
- Gemfile.lock
> [NO-JIRA] Upgrade bundler gem

- package-lock.json
- package.json
This version has the changes from [my PR](https://github.com/typicode/husky/pull/837) to upgrade `find-versions` in Husky.
+ [x] Tests
_If you are …
> [No JIRA] Upgrade Husky

- Example/Backpack/Gradients.storyboard
- Example/Backpack/NavigationData.swift
This is based on #864 so it needs to be merged first.
+ [ ] Tests …
> BPK 4298 add gradient subitems

- Backpack/Button/Classes/BPKButton.m
- Backpack/Card/Classes/BPKCardDivider.m
- Backpack/Chip/Classes/BPKChip.m
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItemDefault.m
- Example/Backpack/Views/HorizontalNavigationItemWithBackground.swift
These checks are redundant as the minimum target version is 12.0
+ [x] Tests …
> [NO-JIRA] Remove iOS 12 checks

- Backpack.podspec
- Backpack/BottomSheet/Classes/BPKFloatingPanelPosition.swift
- Backpack/BottomSheet/Classes/BottomSheet.swift
- Backpack/BottomSheet/Classes/ModalBottomSheetLayout.swift
- Backpack/BottomSheet/Classes/PersistentBottomSheetLayout.swift
- Backpack/BottomSheet/README.md
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/BottomSheet.storyboard
- Example/Backpack/ViewControllers/Bottom Sheet/BottomSheetPersistentViewController.swift
- Example/Backpack/ViewControllers/Bottom Sheet/BottomSheetViewController.swift
- Example/Podfile.lock
- UNRELEASED.md
This PR has the objective to introduce a new style of presentation to BottomSheet. Now we are capable to present it modally or persistently.
It can be initialized by using
```Swift
let bottomSheet = BPKBottomSheet(contentViewController: viewController, 
scrollViewToTrack: viewController.tableView, 
bottomSectionViewController: nil, 
presentationStyle: .persistent)
```
To use the `.persistent` presentation style we need to ensure to use the method `addPanel` instead of `present`.
This will allow the following behavior. 
- New parameter in the initialization called `presentationStyle` which is an enum
```Swift
public enum PresentationStyle {
case modal
case persistent
}
```
- New layout definition: `ModalBottomSheetLayout` and `PersistentBottomSheetLayout`
- New `addPanel(toParent parent: …
> Add Persistent and Modal Presentation Style

- .github/workflows/ci.yml
> [BPK-4402] Make bundle cache machine specific

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarCell.m
- Backpack/Calendar/Classes/BPKCalendarCellSpacing.h
- Backpack/Calendar/Classes/BPKCalendarCellSpacing.m
> [BPK-4397] Refactor calendar cell size constants

- .github/pull_request_template.md
- .github/workflows/ci.yml
- .jirabot.yml
- Backpack/FlareView/Classes/BPKFlarePath.m
- CONTRIBUTING.md
- Rakefile
- decisions/README.md
- scripts/download-relative-fonts
> [BPK-4401]: Migrate to main branch

- Example/Backpack/NavigationData.swift
- Example/Backpack/ViewControllers/CalendarViewController.swift
> [BPK-4399] add preselected dates example

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/NavigationData.swift
- Example/Backpack/Stories/ButtonStory.swift
- Example/Backpack/Stories/CalendarStory.swift
- Example/Backpack/Stories/CardStory.swift
- Example/Backpack/Stories/ChipStory.swift
- Example/Backpack/Stories/DividedCardStory.swift
- Example/Backpack/Stories/FlareStory.swift
I haven't done any of the other components as it looks like they aren't migrated to the navigation format anyway.
> [No Jira] Migrate button, card, calendar and flare to new story format

- Backpack/Calendar/Classes/BPKCalendarCell.m
- UNRELEASED.md
> [BPK-3546] Fix calendar accessibility properties

- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/NavigationData.swift
- Example/Backpack/Stories/ButtonStory.swift
- Example/Backpack/Stories/CalendarStory.swift
- Example/Backpack/Stories/CardStory.swift
- Example/Backpack/Stories/ChipStory.swift
- Example/Backpack/Stories/ColorsStory.swift
- Example/Backpack/Stories/DividedCardStory.swift
- Example/Backpack/Stories/FlareStory.swift
- Example/Backpack/StoryGroup.swift
PoC where I migrate a single story – colours – to this new format.
> [No Jira] Refactor Story protocol to work better with single stories

- Example/SnapshotTests/BPKMapAnnotationSnapshotTest.m
- UNRELEASED.md
> [NO-JIRA] Map test fixes

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarCell.h
- Backpack/Calendar/Classes/BPKCalendarCell.m
- Backpack/Calendar/Classes/BPKCalendarPriceLabelCell.m
- UNRELEASED.md
> [BPK-3546] Make price labels available to AT

- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- UNRELEASED.md
> [NO-JIRA] Expose calendar scrollToDate method

- .spelling
- Backpack/Calendar/Classes/BPKCalendar.h
- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.h
- Backpack/Calendar/Classes/BPKCalendarSelectionConfiguration.m
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.h
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationMultiple.m
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.h
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationRange.m
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.h
- Backpack/Calendar/Classes/BPKCalendarSelectionConfigurationSingle.m
- Backpack/Calendar/README.md
- Example/Backpack/ViewControllers/CalendarViewController.swift
- Example/SnapshotTests/BPKCalendarSnapshotTest.m
- Example/Tests/BPKCalendarSelectionTests.m
- UNRELEASED.md
- migration-guides/42.0.0-migration-guide.md
> Bpk 4426 add calendar accessibility strings

- Example/Backpack Screenshot/Screenshots.swift
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/NavigationData.swift
- Example/Backpack/Stories/MapStory.swift
- Example/Backpack/ViewControllers/MapViewController.swift
> [BPK-4456] Add map performance story

- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/ViewControllers/ColorsViewController.swift
- Example/Backpack/Views/BPKBadgeContainer.swift
- Example/Podfile
- Example/Podfile.lock
> [KOA-4558] Update Example pod dependencies

- package-lock.json
- package.json
> [KOA-4558] update eslint d

- Backpack/Nudger/Classes/BPKNudger.m
- Backpack/Nudger/Classes/BPKNudgerConfiguration.h
- Backpack/Nudger/Classes/BPKNudgerConfiguration.m
- Backpack/Nudger/README.md
- Example/Backpack/ViewControllers/NudgerViewController.swift
- Example/SnapshotTests/BPKNudgerSnapshotTest.m
- Example/Tests/BPKNudgerTest.m
- UNRELEASED.md
https://user-images.githubusercontent.com/30267516/116225428-b79e7b00-a749-11eb-83d1-2fc6a8a3429f.mov
+ [x] Tests
_If you are curious about how we review, …
> [KOA-4562] Fix nudger for Voice Control

- .eslintrc
- dangerfile.js
- gulpfile.js
- package-lock.json
- package.json
> [KOA-4558] Replace eslint-config

- scripts/build-ipa
- scripts/download-relative-fonts
- scripts/set-appcenter-key
- scripts/update-project-for-building-ipa
> [KOA-4518] Add script for setting pbxproj values

- package-lock.json
- package.json
- scripts/upload-ipa-to-appcenter
> [NO-JIRA] Add app-center script

- CONTRIBUTING.md
- Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Screenshot.xcscheme
- Example/Snapfile
- Rakefile
> [KOA-4489] Fix snapshot testing status bar

- .spelling
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItemDefault.m
- Backpack/Icon/Classes/BPKIcon.h
- Backpack/Icon/Classes/BPKIcon.m
- Backpack/Icon/Classes/BPKIconView.h
- Backpack/Icon/Classes/BPKIconView.m
- Backpack/Icon/Classes/BPKLargeIconView.h
- Backpack/Icon/Classes/BPKLargeIconView.m
- Backpack/Icon/Classes/BPKSmallIconView.h
- Backpack/Icon/Classes/BPKSmallIconView.m
- Backpack/Icon/Classes/BPKXlIconView.h
- Backpack/Icon/Classes/BPKXlIconView.m
- Backpack/Icon/README.md
- Backpack/StarRating/Classes/BPKStar.m
- Example/Backpack/ViewControllers/Bottom Sheet/BottomSheetPersistentViewController.swift
- Example/Backpack/ViewControllers/DialogViewController.swift
- Example/Backpack/ViewControllers/IconsViewController.swift
- Example/Backpack/ViewControllers/NavigationBarViewController.swift
- Example/Backpack/ViewControllers/SnackbarViewController.swift
- Example/Backpack/Views/CollectionView Cells/IconsPreviewCollectionViewCell.swift
- Example/SnapshotTests/BPKIconSnapshotTest.m
- Example/SnapshotTests/BPKIconViewSnapshotTest.m
- Example/Tests/BPKIconTest.m
- Example/Tests/IconSwiftTest.swift
- UNRELEASED.md
- migration-guides/icon-migration-guide.md
> [KOA-4293] Add separate icon views for each size

- Example/Backpack/Settings.storyboard
- Example/Backpack/ViewControllers/SettingsViewController.swift
> [NO-JIRA] Add version to example app settings

- CONTRIBUTING.md
The purpose of this PR is to update the CONTRIBUTING.md to align the versions for testing with the CI version currently being used.
> [NO JIRA]: Fix contributing guide for iOS versions

- Backpack-Fonts/Scripts/download-relative-fonts.rb
> [NO-JIRA] Fix font-pulling script

- Backpack/Chip/Classes/BPKChip.h
- Backpack/Chip/Classes/BPKChip.m
- Backpack/Chip/README.md
- Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native.xcscheme
- Example/Backpack/BPKAppDelegate.m
- Example/Backpack/ViewControllers/ChipsViewController.swift
- Example/Backpack/Views/CollectionView Cells/ChipPreviewCollectionViewCell.swift
- UNRELEASED.md
> [KOA-4652] Migrate BPKChip to new icon api

- Example/Backpack/AppStructure.swift
- Rakefile
> [No JIRA] Fix Analysis issues

- Example/Backpack/AppStructure.swift
- Rakefile
Reverts Skyscanner/backpack-ios#1003
Sorry, I'm an idiot
> Revert "[No JIRA] Fix Analysis issues"

- .github/workflows/ci.yml
- Example/Backpack/AppStructure.swift
- Example/SnapshotTests/BPKSnapshotTest.h
- Example/SnapshotTests/BPKSnapshotTest.swift
- Rakefile
> upgrade ci

- CONTRIBUTING.md
> [NO-JIRA] Add swift to contributing guide

- Backpack/TabBarController/Classes/BPKTabBarController.m
- UNRELEASED.md
> [KOA-4714] Add missing TabBar super call

- .spelling
- Backpack/Toast/Classes/BPKToast.h
- Backpack/Toast/Classes/BPKToast.m
- Backpack/Toast/README.md
- Example/Backpack/ViewControllers/ToastViewController.swift
- Example/SnapshotTests/BPKToastSnapshotTest.m
- UNRELEASED.md
> [KOA-4422] Improve Toast with VoiceOver

- Example/Backpack.xcodeproj/xcshareddata/xcschemes/Backpack Native.xcscheme
> [KOA-4746] Randomise test running order

- CONTRIBUTING.md
Document iOS/Xcode upgrade process.
+ [x] Tests
> [KOA-4746] Document iOS/Xcode upgrade process

- Example/Backpack/AppStructure.swift
- Example/Backpack/NavigationData.swift
Document state of stories.
+ [x] Tests …
> KOA 4746 document state of stories

- CONTRIBUTING.md
> [KOA-4746] Fix markdown link

- .spelling
- ARCHITECTURE.md
> Document project architecture in ARCHITECTURE.md

- .github/workflows/ci.yml
This was failing for non-team members and wasn't providing a lot of value.
+ [x] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [x] Tests
_If you are curious about how we review, please read through the …
> Clean up docs deploy step for PRs

- .github/pull_request_template.md
The contributions link was incorrect and linked to the android guidelines
+ [ ] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-android/blob/main/CONTRIBUTING.md)
+ [ ] Tests
_If you are curious about how we review, please read through the …
> [NO-JIRA] Fix the contributions link in the PR template

- Backpack.podspec
- Backpack/TextField/Classes/BPKTextField.m
- CHANGELOG.md
- Example/Podfile.lock
- Rakefile
Only applying border width if the borderstyle is not none. Setting it to it's default value if it is none
> Fix: only applying border width if the borderstyle is not none

- Example/Backpack NativeUITests/CalendarUITest.swift
- Example/Backpack.xcodeproj/project.pbxproj
- Example/Backpack/Stories/CalendarStory.swift
- Example/Backpack/ViewControllers/CalendarViewController.swift
- UNRELEASED.md
Adding UI Tests for Happy paths on Calendar
+ [x] Tests
> [KOA-3844] calendar UI tests

- .nvmrc
- UNRELEASED.md
- package-lock.json
- package.json
Upgrade the node engines to the current lts.
- Upgrade to node version 16.13.0
- Upgrade to NPM version 8.1.0
- Remove the ensure-node-env check
+ [ ] Tests …
> [KOA-5031] Upgrade to node 16

- Backpack-Common.podspec
- Backpack-Common/DummyToken/Classes/DummyToken.swift
- Example/Podfile
- Example/Podfile.lock
- Rakefile
- UNRELEASED.md
Adding the Common Module.
For now it will be empty until we need to add shared code to it.
+ [x] Tests
_If you are curious about how we review, please read …
> Koa 5034 commons module

- gulpfile.js
- scripts/gulp/borderWidths.js
- scripts/gulp/colours.js
- scripts/gulp/durations.js
- scripts/gulp/dynamicColours.js
- scripts/gulp/fonts.js
- scripts/gulp/generation/objc.js
- scripts/gulp/iconNames.js
- scripts/gulp/radii.js
- scripts/gulp/shadows.js
- scripts/gulp/spacings.js
- scripts/gulp/utils/formatUtils.js
- scripts/gulp/utils/legibleName.js
Gulpfile was big and hard to follow and to make it grow. cleaning it up a bit so that's easier to handle and to add swiftui code to it when needed
+ [x] Tests
+ [x] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up …
> separating gulp into multiple files to improve reading

- Backpack-Common/Icons/Generated/BPKAutoMirrorIconNames.swift
- gulpfile.js
- scripts/gulp/autoMirrorIconNames.js
- templates/BPKAutoMirrorIconNames.njk
Create gulp script to generate the needed files in Backpack-Common. 
+ [x] Tests …
> KOA-3425 create script to generate auto mirror icons

- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationTypes.swift
Change the fontStyle for horizontal navigation to label2 for default size
+ [ ] Tests …
> KOA-4971 Horizontal navigation typography fix

- .github/workflows/_build.yml
- .github/workflows/release.yml
Move the docs step into release
+ [ ] Tests …
> KOA-5168 move docs publish step

- .github/workflows/release.yml
Run bundle install, so we can use our dependencies when releasing docs
+ [ ] Tests …
> KOA-5168 Install cocoapods from bundle

- .github/workflows/_build-docs.yml
- .github/workflows/_build.yml
- scripts/lint
We weren't pod installing before building uikit, so in some cases, the project can be out of date.
+ [ ] Tests
_If you are curious about how we review, please read through the …
> pod installing before building uikit

- .github/workflows/_build-docs.yml
- .github/workflows/_build.yml
In some cases the cache is not correct and installation needs to happen, it will be fast though, since useful dependencies would be cached (but reinstalled)
+ [ ] Tests
_If you …
> always run pod and bundle install

- .github/workflows/release.yml
Script was out of date, calling something that no longer exists.
+ [ ] Tests …
> No jira fixing docs deployment release

- .github/workflows/release.yml
> building and deploying docs as part of pod deployment

- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigation.swift
- Backpack/HorizontalNavigation/Classes/BPKHorizontalNavigationItemDefault.swift
Update to semantic tokens
+ [ ] Tests
_If you are curious about how we review, please read through the [code review guidelines](https://github.com/Skyscanner/backpack/blob/main/CO …
> KOA-5532 Update BPKHorizontalNavigation

- Backpack-SwiftUI/Color/Classes/Generated/BPKDynamicColors.swift
- Backpack/Color/Classes/Generated/BPKColor.h
- Backpack/Color/Classes/Generated/BPKColor.m
- Backpack/Color/Classes/Generated/UIColor+Backpack.h
- package-lock.json
- package.json
Updated surface contrast dark colour to night grey 10
> Update surface contrast colour

- scripts/build-docs
[KOA5645] Copying docs to latest folder to be able to navigate to a specific file from the docsite
> [KOA5645] Copying docs to latest folder

- .github/workflows/release.yml
> clonning before executing docs release

- Backpack-SwiftUI/Card/README.md
Update README.md of Backpack-SwiftUI/Card
Changes:
* Add screenshots of `BPKDividedCard`
* Insert a blank line between bold text and normal text to force a line break
+ [ ] Tests …
> Update README.md of Backpack-SwiftUI/Card

- Backpack/Badge/README.md
> Update image size in readme

- Backpack-SwiftUI/Radii/Classes/Generated/BPKRadii.swift
- Backpack-SwiftUI/Tests/Radii/RadiiTests.swift
- Backpack/Radii/Classes/Generated/BPKRadii.h
- Backpack/Radii/Classes/Generated/BPKRadii.m
- Backpack/Tests/UnitTests/BPKRadiiTest.m
- Example/Backpack/SwiftUI/Tokens/RadiusTokensView.swift
- Example/Backpack/UIKit/Tokens/RadiusTokensViewController.swift
- package-lock.json
- package.json
> [KOA-5839] Removing pill radii

- Backpack/Icon/README.md
- Backpack/Tests/SnapshotTests/BPKTappableLinkLabelSnapshotTest.swift
- CONTRIBUTING.md
- Example/Backpack/UIKit/Components/Link/TappableLinkLabelsViewController.swift
- README.md
> [KOA-5649] Remove references to backpack.github.io

- Backpack/NavigationBar/README.md
> Update BPKNavBar README.md

- .github/workflows/release.yml
- CONTRIBUTING.md
> [KOA-5959] Automate Supernova docs publish

- package-lock.json
- package.json
> Add supernova as a dependency

- .github/workflows/release.yml
- package-lock.json
- package.json
Currently the Supernova deploy step fails due to the way the CLI is installed and the way the command is accessed. In it's current form it is only installed locally but accessed as a global module.
So this PR changes to use `npx` which will install globally on the fly and allow us to use the command in it's simple form without either creating more commands or direct node_module access.
+ [ ] Tests
+ [ ] Adding a component? Remember to expose it in the [main …
> [NO JIRA]: Fix supernova doc deployment step

- Backpack/Rating/Classes/BPKRating.swift
> [KOA-5994] Making the title not required in bpkrating

- CONTRIBUTING.md
> [KOA-5970] Add experimentation guidelines

- Backpack/Card/Classes/BPKDividedCard.h
- Backpack/Card/Classes/BPKDividedCard.m
> Add support for setting distribution of BPKDividedCard

- .github/workflows/_build-docs.yml
- .github/workflows/_build.yml
- .nvmrc
- package-lock.json
- package.json
> [KOA-6077] Node 18 update

- CONTRIBUTING.md
> Update CONTRIBUTING.md experimentation guidelines

- Backpack-SwiftUI/Card/Classes/BPKCard.swift
Fix accessibility, by not ignoring content of BPKCard
+ [ ] Tests
> SwiftUI BPKCard

- Backpack/Calendar/Classes/BPKCalendar.m
- Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.h
- Backpack/Calendar/Classes/BPKCalendarMonthDateProvider.m
- Backpack/Tests/UnitTests/BPKCalendarMonthDateProviderTests.swift
> fixing invalid whole month selection

- Backpack-SwiftUI/Card/Classes/BPKCard.swift
- Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
> [NoJira] Cards are no buttons anymore

- Backpack-SwiftUI/Card/Classes/BPKCard.swift
- Backpack-SwiftUI/Card/Classes/BPKDividedCard.swift
Reverts Skyscanner/backpack-ios#1754
> Revert "[NoJira] Cards are no buttons anymore"

- Backpack/Calendar/Classes/BPKYearMonth.swift
I merge a PR this morning that contains an issue on how things are compare.
This PR is here to fix that.
+ [ ] Tests
> OGM-1921: Fix issues when comparing dates

- .github/workflows/_build.yml
- scripts/ci
A previous attempt to disable UITests done here missed out actually disabling them correctly, this does it.
https://github.com/Skyscanner/backpack-ios/pull/1833
> [NoJira] Properly disable UITests

- Backpack-SwiftUI/AppSearchModal/Classes/AppSearchModalContentView.swift
This pull request adds a content shape to the AppSearchModalContentView in order to improve the accessibility and user experience.
> Add content shape to AppSearchModalContentView

- Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView+Style.swift
- Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
- Backpack-SwiftUI/NavigationBar/Classes/CollapsedNavigationBar.swift
- Backpack-SwiftUI/NavigationBar/Classes/ExpandedNavigationBar.swift
- Backpack-SwiftUI/NavigationBar/Classes/NavBarScrollViewWithOffset.swift
- Backpack-SwiftUI/Tests/NavBar/BPKNavigationViewTests.swift
[No jira]
Cleaning up the Navbar's code and also fixing an issue where the scrollview clips the bottom content because we're manually dealing with the offsets.
> Fixing scrolling issue and cleanup

- Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView+Style.swift
- Backpack-SwiftUI/NavigationBar/Classes/BPKNavigationView.swift
- Backpack-SwiftUI/NavigationBar/Classes/ObservableScrollView.swift
This pull request refactors the BPKNavigationView to better support the transparent style. It includes changes to the BPKNavigationView+Style.swift and BPKNavigationView.swift files. The changes ensure that the navigation view correctly handles the transparent style and adjusts the vertical offset accordingly. Additionally, a new ObservableScrollView struct is added to handle scrolling behavior.
> Refactor BPKNavigationView to support transparent style better

- Backpack-Common/Carousel/Classes/CarouselPageViewController.swift
- Backpack-SwiftUI/Carousel/Classes/BPKCarousel.swift
- Backpack/Carousel/Classes/BPKCarousel.swift
- Backpack/PageIndicator/Classes/BPKPageIndicator.swift
- Allow the index of the carousel to change when done through accessibility gestures
- Fix animation direction when page index is changed, this is now contextual based on page index
+ [ ] Tests …
> [BPKCarousel] ACC-464 fix Carousel Accessibility defects

- Backpack-SwiftUI/CarouselCard/Classes/BPKCarouselCard.swift
> [AI-643] [ChAI]: Add accessibility to new CarouselCard

- Backpack-SwiftUI/SearchInputSummary/Classes/BPKSearchInputSummary.swift
- Backpack-SwiftUI/SearchInputSummary/README.md
> BPKSearchInputSummary accessibility improvement

- Backpack-SwiftUI/Icons/Classes/Generated/BPKIcons.swift
- templates/swiftui/BPKIcons.njk
This PR creates a separate method for custom icons.
+ [X] Check this if you have read and followed the [contributing guidelines](https://github.com/Skyscanner/backpack-ios/blob/main/CONTRIBUTING.md)
+ [X] `README.md`
+ [ ] Tests
> TEMPURA-2186: Create separate method for custom icons

- .github/workflows/_build.yml
- .github/workflows/_test.yml
- .github/workflows/label-check.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Applying the same changes as Skyscanner/backpack-android#2195 provided by Catalyst to use the Github App for CI
> SDPLAT-26630: use github app in workflows

- .github/workflows/_build.yml
- .github/workflows/_test.yml
- .github/workflows/snapshot.yml
> Updates Save Snapshots to use user token

- Backpack-SwiftUI/BottomSheet/Classes/ContentFitBottomSheet.swift
- Backpack-SwiftUI/BottomSheet/Classes/KeyboardAvoidingViewModifier.swift
> AI-1071: Set background color to bottom sheet

- .github/dependabot.yml
Update dependabot workflow to avoid automatic label issues
+ [ ] Tests
> Update dependabot workflow to avoid automatic label issues

- Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
> DON-1074: Fix accessibility formatter in backpack

- Backpack-SwiftUI/Calendar/Classes/Range/RangeCalendarContainer.swift
> DON-1569: Fix isSelected for BPKCalendar

- Backpack-SwiftUI/Calendar/Classes/BPKCalendar.swift
- Backpack-SwiftUI/Calendar/Classes/Core/CalendarContainer.swift
- Backpack-SwiftUI/Calendar/Classes/Core/CalendarTypeContainerFactory.swift
- Backpack-SwiftUI/Calendar/README.md
> DON-1636: Return all visible months with onScrollToMonth

- Example/Backpack.xcodeproj/project.pbxproj
> Fix project.pbxproj

- Backpack-Common/Configuration/Classes/BPKConfiguration.swift
This PR (PoC) is calling an event when configuration is accessed for the first time.
> [DON-2013] (PoC) Add Backpack configuration-accessed event

- Backpack-SwiftUI/TappableContainer/Classes/BPKTappableContainer.swift
- Backpack-SwiftUI/TappableContainer/Classes/UIView+TappableContainer.swift
Update of the TappableContainer wrapper to fix some accessibility issues
+ [ ] Tests
> Update wrapper to fix accessibility
